### ISSUE TITLE
no-banner CLI option doesn't work

### ISSUE THREAD

**Issue by daviddelusenet** [timocov/dts-bundle-generator#107]
**Bug report**
Thanks for releasing a new version! However, the newly added `--no-banner` CLI option doesn't work as expected.

This option is also missing from the documentation and it would be nice if you could set this option from the `dtsconfig.json` also.

**Input code**
**NPM script**
```bash
./node_modules/.bin/dts-bundle-generator --no-banner --config=dtsconfig.json
```

**Output**
```ts
// Generated by dts-bundle-generator v4.0.0

Types here..
```

**Expected output**
```ts
Just the types
```

I'm using version 4.0.

**Comment by timocov** [comment]
Hmm, let me check...

**Comment by timocov** [comment]
Ah, `--no-banner` doesn't override value from the config. I'll make fix soon and update docs as well. Thank you!

**Comment by timocov** [comment]
You can add `noBanner` option to `output` options for each entry - see schema https://unpkg.com/browse/dts-bundle-generator@4.0.0/config-schema.d.ts.

**Comment by daviddelusenet** [comment]
@timocov thanks for the quick responses!

If you're going to update to documentation maybe also add documentation for the `inlineDeclareExternals` option to the [config file page](https://github.com/timocov/dts-bundle-generator/blob/master/src/config-file/README.md).

**Comment by timocov** [comment]
Yeah, sure! Thank you for pointing out missing docs. It's so easy to just forget to update they 😂 See 64b1a2d3deaf082c26dd0fc9f148190f76dc848c

**Comment by timocov** [comment]
I don't think that it requires to publish the new version with that fixes, as soon it's only docs update. If you'll something wrong with v4 - please let me know 🙏
