### ISSUE TITLE
Does.  dts config: inlinedLibraries support inline @types/package?

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#108]
i saw the config (inlinedLibraries: ['fake-package']) , can it works packages which as dts definitions within @types/xxxxx? 
```
    //. configurations
    libraries: {
        inlinedLibraries: ['yargs', 'inquirer'],
      },
   // import { Arguments } from 'yargs';
```
the yargs is has @types/yargs dts mapping, it throws error

**Comment by timocov** [comment]
> inlinedLibraries: ['yargs', 'inquirer'],

Does it work?

> it throws error

What error?

**Comment by tianyingchun** [comment]
for example:
the
  packages/
     + common (will export utilities from yargs) package.json <-- @types/yargs, yargs
     + cli (depends `common`) and export new item, it will throw error
```
src/commands/serve/builder.ts(4,14): error TS2742: The inferred type of 'serveCmd' cannot be named without a reference to '@flatjs/common/node_modules/@types/yargs'. This is likely not portable. A type annotation is necessary.
```

**Comment by tianyingchun** [comment]
do you have any ideas for this?

**Comment by tianyingchun** [comment]
oh, i find a way to resolve this issue, make alias and re-export yargs from `@flatjs/common`
like  
``` ts
```

**Comment by timocov** [comment]
> cause of. createCmdBuilder() depends CommandModule from @flatjs/common--> @types/yargs
> do you have any ideas for this?

Yes, as stated in the error message `This is likely not portable. A type annotation is necessary` looks like you need to specify type of the variable `serveCmd` in the way `export const serveCmd: TypeHere = ...`.

May I ask you why need to inline types from `@types/yargs`? It looks weird for me as soon they might be just installed in other packages.

**Comment by tianyingchun** [comment]
you are right, the @types/yargs will be installed via jest-js, so i can't found the export const serveCmd: in fact ts lint will throw error to me, the error `his is likely not portable. A type annotation is... ` is throw by typescript .
i have changed the dts config to  below.
```
      libraries: {
        importedLibraries: ['yargs', 'inquirer'],
      },
```

**Comment by tianyingchun** [comment]
BTW i try some dts generator tool, like rollup-bundle-dts, npm-dts, and so on, i like dts-bundle-generator, it simple, no other depends configuration need, it only depends input entry 'src/index.ts'. very very convenient. great job thanks a lot.

**Comment by timocov** [comment]
@tianyingchun Thank you for you feedback! ❤️ I do really appreciate it.
