### ISSUE TITLE
Fix multiple interfaces with the same name

### ISSUE THREAD

**Issue by OmgImAlexis** [timocov/dts-bundle-generator#120]
This plugin does something similar but it doesn't have the issue with having multiple interfaces with the same name. For example `interface Options` will be changed to `interface Options$1` I haven't had any issues with that since using their plugin.

https://github.com/Swatinem/rollup-plugin-dts

**Comment by timocov** [comment]
Sorry for long reply. Yeah, it's [the first known limitation](https://github.com/timocov/dts-bundle-generator#known-limitations) of the tool and I'm not sure whether it's easy to fix it. Afaik `rollup-plugin-dts` uses rollup under the hood to solve the original problem (bundling dts).

**Comment by timocov** [comment]
Actually it's duplicate of #116
