### ISSUE TITLE
`import Foo = require("foo")` does not appear to work

### ISSUE THREAD

**Issue by cspotcode** [timocov/dts-bundle-generator#122]
I'm trying to use dts-bundle-generator to bundle type declarations which do `import Liftoff = require("liftoff");`  It does not appear to be recognizing and including the `import ... = require(...)` statement.

I believe this style of import is required because Liftoff's declarations do `export =` instead of named exports.

I saw that #60 fixed doing `export =`, so I guess my problem is the opposite: the `import ... = require()` is ignored.

Is this a known limitation, or is there anything I should do to debug or reproduce the issue?

**Comment by timocov** [comment]
Looks like a bug. Can you please provide full sample what exactly is going wrong? I mean, repro of the issue.

**Comment by timocov** [comment]
5.1.0 version with the fix is just published https://github.com/timocov/dts-bundle-generator/releases/tag/v5.1.0

**Comment by cspotcode** [comment]
Thanks!  Yes, I'm always glad to provide reproductions in the future.
