### ISSUE TITLE
Import from "events" but the /// <reference types="node"/> is omitted

### ISSUE THREAD

**Issue by cspotcode** [timocov/dts-bundle-generator#123]
**Bug report**

Full reproduction: https://github.com/cspotcode/repros/tree/dts-bundle-generator-reference-node

I have a type declaration which references the "node" type declarations and imports from node's "events" module.  The emitted declaration includes the `import {EventEmitter} from "events"` but not the `/// <reference types="node" />` so there are compiler errors with the emitted declaration.

Am I don't something wrong?

**Input code**

```ts
/// <reference types="node" />
import { EventEmitter } from 'events';

export class MyEventEmitter extends EventEmitter {}
```

**Expected output**

```ts
// Generated by dts-bundle-generator v5.1.0
/// <reference types="node" />
import { EventEmitter } from 'events';

export class MyEventEmitter extends EventEmitter {}

export {};
```

**Actual output**

The `/// <reference>` is missing.

```ts
// Generated by dts-bundle-generator v5.1.0

import { EventEmitter } from 'events';

export class MyEventEmitter extends EventEmitter {}

export {};
```

**Comment by timocov** [comment]
Hm, interesting. I think that the reason of check error is that `types` is an empty array in tsconfig file, and I don't know how it'll work when that generated file will be in node_modules and will be used by another package in both cases: when `types` array is empty and when it has `node` in it. But anyway I think that it might be easily fixed.

**Comment by timocov** [comment]
[The version 5.2.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v5.2.0) with fixes is just published.
