### ISSUE TITLE
Inlining of `export = foo` when it's `declare namespace foo`

### ISSUE THREAD

**Issue by cspotcode** [timocov/dts-bundle-generator#124]
**Bug report**

Reproduction here: https://github.com/cspotcode/repros/tree/dts-bundle-generator-ora

When a third-party .d.ts declares `namespace ora {}; export = ora;` the contents of the namespace aren't bundled correctly.

In my case, I'm trying to bundle the declarations for `ora`.  It exports a function that is also a namespace.  In my reproduction, I simplified the ora declarations to the bare minimum.
Full ora declaration: https://unpkg.com/ora@4.0.5/index.d.ts
Minimized declaration in my reproduction: https://github.com/cspotcode/repros/blob/dts-bundle-generator-ora/node_modules/ora/index.d.ts

I tried removing the function declaration and the issue still occurs, so I think it is limited to `export = ` of a namespace.

**Input code**

```ts
import { Options } from 'ora';

export const ExportedValue: Options;
export type ExportedType = Options;
```

**Expected output**

```ts
// Generated by dts-bundle-generator v5.1.0
interface Options {}
export const ExportedValue: Options;
export type ExportedType = Options;

export {};
```

**Actual output**

`Options` declaration omitted.

```ts
// Generated by dts-bundle-generator v5.1.0

export const ExportedValue: Options;
export type ExportedType = Options;

export {};
```

**Comment by cspotcode** [comment]
I'm not sure if this is related to #122.  #122 was about including the import, whereas this issue is about inlining the imported types.  My reproduction is using the latest 5.1.0 that you published recently.

**Comment by timocov** [comment]
Sorry for late response. I think it's related to #11 actually. `Options` interface is declared inside a namespace and quite probably that it's the reason.

**Comment by cspotcode** [comment]
In #11, the namespace is bundled, and it includes extraneous, unused declarations.  In this issue, the namespace has been omitted.  Is that correct?

**Comment by timocov** [comment]
Yes, that's correct. I meant, there are some problems and namespaces (modules), this is just another one issue I guess. I'll take a look at this issue after #123 and will back with results soon.

**Comment by timocov** [comment]
@cspotcode Is that important for you that `interface Options {}` from `ora` package shouldn't be exported (in your expected output you marked it as non-exported so that's why I'm asking)? It seems that the tool doesn't supported it yet (non-exported interfaces, so all interfaces/types are exported by default). It seems that #127 fixes the issue, but `Options` is exported though.

**Comment by timocov** [comment]
[The version 5.2.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v5.2.0) with fixes is just published.
