### ISSUE TITLE
About config `importedLibraries` for module of  `lerna packages `

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#135]
hi , i have question about the typings imports:  consider below sense.

i using lerna to `Symlinks`  node modules `@flat/mock`, `@flat/evolve` and with tsconfig.json
```
 "paths": {
      "@flat/mock": [
        "packages/mock/src"
      ],
   "@flat/evolve": [
        "packages/evolve/src"
      ],
```
packages
   + mock
   + evolve

i imported some typings from `@flat/mock` in `@flat/evolve`, all typings will inline imported from `@flat/mock` instead using `import {xx} from @flat/mock` in index.d.ts, even if i have setup
importedLibraries: ['@flatjs/mock'],  and disabled `followSymlinks`

do you have som suggestion about this?

**Comment by timocov** [comment]
Sorry for late reply. Can you please prepare a repro for that?

**Comment by tianyingchun** [comment]
sorry for late, i have resolved this issue by reset `paths`: to an emtpy object `{}` in compilerOptions for `tsconfig.json`, it works fine, BTW can you provider some configurations to override default `compilerOptions` of  ` tsconfig.json like `followSymlinks` in `BundlerConfig`

**Comment by tianyingchun** [comment]
like: 
```
const dtsBundle = {
  compilationOptions: {
    followSymlinks: false,
... provider another standand `compilerOptions` to override ` tsconfig.json`
  },
  entries: [ ....]
}

```

**Comment by timocov** [comment]
@tianyingchun I just created #137 for that.
