### ISSUE TITLE
allow using globs for file paths

### ISSUE THREAD

**Issue by Milo123459** [timocov/dts-bundle-generator#136]
I want to compile all my .d.ts files which is a lot, I tried
dts-bundle-generator <options> dist/**/**.d.ts yet that does not work
please add support for using globs, thanks.

**Comment by Milo123459** [comment]
Also, when running: `dts-bundle-generator -o index.d.ts --project tsconfig.json --no-banner dist/index.d.ts`
I get the error:
Error: Symbol for root source file dist/index.d.ts not found
index.d.ts is the following:
```ts
//# sourceMappingURL=index.d.ts.map
```
index.d.ts.map
```
{"version":3,"file":"index.d.ts","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":""}
```

**Comment by timocov** [comment]
If you'd like to make a bundle from all of your d.ts files, just create a file with re-exports from all that files.

**Comment by Milo123459** [comment]
Okay. Thanks.
