### ISSUE TITLE
Declaration files not identified as a RootSourceFile

### ISSUE THREAD

**Issue by iFaxity** [timocov/dts-bundle-generator#138]
**Bug report**

Hi, i could not really glance from the documentation how to deal with including external declarations files, ive put 

From debugging on my own i can see the file is being correctly parsed, but seems to be flagged as a non root
 source file (the flags property on the SourceFileObject is 8388672).

Is this intended and which other way can i add external declaration types other than using the triple slash reference?

**Input code**

```ts
// from my build script
      const typings = generateDtsBundle([
        { filePath: path.resolve('globals.d.ts'), },
        { filePath: path.resolve('src/index.ts'), },
      ], {
        preferredConfigPath: path.resolve(__dirname, '../tsconfig.json'),
        externalTypes: [ 'node', '@vue/reactivity' ],
        externalImports: [ '@vue/reactivity' ],
      });
```

```ts
// globals.d.ts

interface ShadyCSS {
  nativeCss: boolean;
  nativeShadow: boolean;
  styleElement(host: Element, properties?: Record<string, string>): void;
  styleSubtree(element: HTMLElement, properties?: Record<string, string>): void;
  prepareTemplateDom(template: HTMLTemplateElement, name: string): void;
  prepareTemplate(template: HTMLTemplateElement, name: string, elementExtends?: string): void;
  prepareTemplateStyles(template: HTMLTemplateElement, name: string, elementExtends?: string): void;
  ScopingShim?: {
    prepareAdoptedCssText(cssText: string[], name: string): void;
  };
}

interface ShadyDOM {
  inUse: boolean;
  flush: () => void;
}

interface CSSStyleSheet {
  replaceSync(cssText: string): void;
  replace(cssText: string): Promise<unknown>;
}

interface ShadowRoot {
  adoptedStyleSheets: CSSStyleSheet[];
}

declare var ShadowRoot: { prototype: ShadowRoot; new (): ShadowRoot; };

interface Window {
  ShadyCSS?: ShadyCSS;
  ShadyDOM?: ShadyDOM;
  ShadowRoot: typeof ShadowRoot;
}

// Globals for identifying versions in builds
declare var __DEV__: boolean;
declare var __BROWSER__: boolean;
declare var __NODE_JS__: boolean;
declare var __VERSION__: string;
```

**Expected output**

Expected file to be generated without errors (hopefully).

**Actual output**

Error from console:
```
Error: Symbol for root source file <project>/packages/globals.d.ts not found
    at <project>/node_modules/dts-bundle-generator/dist/bundle-generator.js:45:19
    at Array.map (<anonymous>)
    at generateDtsBundle (<project>/node_modules/dts-bundle-generator/dist/bundle-generator.js:36:20)
    at build (<project>/bin/build:151:23)
    at async run (<project>//bin/build:188:7) {stack: 'Error: Symbol for root source file <project>/bin/build:188:7)', message: 'Symbol for root source file <project>/packages/globals.d.ts not found'}
```

**Additional context**

I'm using the JS api version dts-bundle-generator

versions:
Node: v14.13.1
dts-bundle-generator: v5.4.0
OS: Ubuntu 20.04 (WSL 2), Windows 10 (build 19041.508)

**Comment by timocov** [comment]
Hi,

what you'd expect to see for the output for `globals.d.ts` file? It doesn't export anything though...

Every entry you've passed to `generateDtsBundle` are handled separately (but they all are compiles together, yeah).

**Comment by iFaxity** [comment]
Oh ok i see, i have a ts file and a globals declarations file which contains global interfaces for each package as i have a monorepo which all shares the same globals.d.ts file. But i see if it expects exports in the declaration file (seems correct as i defined it as an entry file in dts-bundle-generator) i might have to add that to the file. Or ill just run with the triple reference comment at the start of the entrypoint instead. As it should be included then as it is explicitly referenced correct?

**Comment by timocov** [comment]
Afaik by default no "global" declaration will be inlined rather than some part of it is used in the generated bundle. I can suggest you to try to do the next trick:

1. Wrap your `globals.d.ts` in `declare global` declaration and put `export {}` after all in this file (to enable "module mode" for a file):

	```ts
	declare global {
	/* your current content here */
	}
	export {};
	```

1. Include this file by using tripple-slash directive `/// <reference path="./relative/path/to/globals.d.ts" />` in every file you use these globals (it's unnecessary to include it in every file basically, but in my opinion it'd be better)
1. Enable `--inline-declare-global` (or `output.inlineDeclareGlobal` in config file) to inline all `declare global` directives to the result bundle.

**Comment by timocov** [comment]
You can see how it's done in test cases https://github.com/timocov/dts-bundle-generator/tree/fd0b12a4e1900cb1a92e7fecd4e054c80a5b7f40/tests/e2e/test-cases/inline-declare-global.

**Comment by iFaxity** [comment]
Ok swet, thanks.
