### ISSUE TITLE
Throw error `Error: Cannot find symbol for node: ChainExpression`

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#151]
**Bug report**
while tsconfig.json set compilerOptions : {skipLibCheck: `true`} 
```ts
const nodeSymbol = this.typeChecker.getSymbolAtLocation(node); 
if (nodeSymbol === undefined) {
			throw new Error(`Cannot find symbol for node: ${node.getText()}`);
		}
```
it will throw error `Error: Cannot find symbol for node: ChainExpression`

**Input code**

```ts
// place your code here
```

**Expected output**

```ts
// place your code here
```

**Actual output**

```ts
// place your code here
```

**Additional context**
Add any other context about the problem here (CLI options, etc)
`dts-bundle-generator@5.8.0`
`typescript@4.2.3`

**Comment by tianyingchun** [comment]
maybe it caused by npm 7

**Comment by chwech** [comment]
> maybe it caused by npm 7

same issue, my npm version is 6.13.4. how to resolve this ?

**Comment by chwech** [comment]
> maybe it caused by npm 7

same issue, my npm version is 6.13.4. how to resolve this ?

**Comment by tianyingchun** [comment]
cause of dts bundle will load all @types/* definitions, once any of @types item has broken it will break. 
you can remove error with @types !
