### ISSUE TITLE
Wrong typings generated when import() is used for types

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#152]
**Bug report**

Bad Typings code generated `npx dts-bundle-generator src/index.ts -o index.d.ts`
[Sample demo is here ](https://github.com/tianyingchun/dts-bundle-issue/tree/master)

**Input code**

`src/index.ts`
-----------------
```ts
export * from './fabric-utils';
export * from './fabric-x';
```

`src/fabric-utils/index.ts`
-----------------
```ts
import { setDebugStatus } from './set-debug';

export const fabricUtils = {
  setDebugStatus,
};
```
`src/fabric-utils/set-debug.ts`
-----------------
```ts
import { FabricDebugCallbackData, FabricDebugOptions } from './type.debug';

export const setDebugStatus = (options: FabricDebugOptions): FabricDebugCallbackData => {
  console.log('options', options)
  return {} as FabricDebugCallbackData;
};

```
`src/fabric-utils/type.common.ts`
-----------------
```ts
export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};

export declare type FabricCallbackData<T extends Json = null> = {

   code: "fabric_catched_error" | string;
  
   data: T;
}
```
`src/fabric-utils/type.debug.ts`
-----------------------------

```ts
import { FabricCallbackData } from './type.common';

export type FabricDebugOptions = {

  enableDebug: boolean;
};


export type FabricDebugCallbackData = FabricCallbackData<{

  enabled: boolean;
}>;

```

**Expected output**

```ts
// Generated by dts-bundle-generator v5.8.0

export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};
export declare type FabricCallbackData<T extends Json = null> = {
	
	code: "fabric_catched_error" | string;
	
	data: T;
};
export declare type FabricDebugOptions = {
	
	enableDebug: boolean;
};

export declare type FabricDebugCallbackData = FabricCallbackData<{
	
	enabled: boolean;
}>;
export declare const fabricUtils: {
	setDebugStatus: (options: FabricDebugOptions) =>  FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};

```

**Actual output**

```ts
// Generated by dts-bundle-generator v5.8.0

export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};
export declare type FabricCallbackData<T extends Json = null> = {
	 
	code: "fabric_catched_error" | string;
	 
	data: T;
};
export declare type FabricDebugOptions = {
	 
	enableDebug: boolean;
};
 
export declare type FabricDebugCallbackData = FabricCallbackData<{
	 
	enabled: boolean;
}>;
export declare const fabricUtils: {
	setDebugStatus: (options: import("./type.debug").FabricDebugOptions) => import("./type.debug").FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};

```

**Additional context**
`typescript@^4.2.3`, `dts-bundle-generator@^5.8.0`

**Comment by timocov** [comment]
Am I right that the problem is that there are `import("./type.debug")` statements instead of actual types?

**Comment by tianyingchun** [comment]
yes if i move these types into export file avoid import `types` it works fine. but i think import("./type.debug") is very common development experience. could you improve this behavior? allow us import `typing` from some individual typing files?

**Comment by Kilcekru** [comment]
I have a very similar issue
The interesting part is that the type itself is correctly exported, so `FabricDebugCallbackData` instead of `import("./type.debug").FabricDebugCallbackData` would immediately work

**Comment by tianyingchun** [comment]
@Kilcekru yes, FabricDebugCallbackData has been exported!:)

**Comment by timocov** [comment]
I'll try to fix it.

**Comment by tianyingchun** [comment]
:) great news again!

**Comment by tianyingchun** [comment]
hi @timocov i have another question about this issue.  it seems that it lose `comments` while import() is used for types
[demo is here](https://github.com/tianyingchun/dts-bundle-issue/tree/master)
while run `npm run dts` build it genereated an correct index.d.ts for typings. but it lose some important `comments` for method. 

tsconfig.json with `removeComment` :false, 
actual result is :
```
....
/**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
	setDebugStatus: (options: FabricDebugOptions) => FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};

```

expect result should be 
```
```
....
/**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
  /**
   * comments for method `setDebugStatus`
   * @param options 
   * @returns 
   */
	setDebugStatus: (options: FabricDebugOptions) => FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};
```
