### ISSUE TITLE
Star import results in an invalid type file

### ISSUE THREAD

**Issue by DataTables** [timocov/dts-bundle-generator#158]
**Bug report**

I've created a [demo repo](https://github.com/DataTables/dts-bundle-generator-star-import) to show the behaviour I'm seeing here.

In short the output from dst-bundle-generator looks like:

```
declare function myMethod(): string;
export default class MyClass {
	myMethod: typeof api.myMethod;
}

export {};
```

But you'll notice that there is no `api` defined, thus the d.ts file is invalid. This is due to the `import * as api from './api';`.

To reproduce in the repo:

```
npm install
npm run tsc
npm run dts
```

Many thanks for any help or thoughts you might be able to provide to help with this. dts-bundle-generator is a really useful piece of software!

**Comment by DataTables** [comment]
Interestingly, I thought I might be able to workaround this by just naming the imports and that does appear to work:

```
import {myMethod} from './api';

export default class MyClass {
  public myMethod = myMethod;
}
```

gives:

```
declare function myMethod(): string;
export default class MyClass {
	myMethod: typeof myMethod;
}
```

But an alias doesn't:

```
import {myMethod as thatMethod} from './api';

export default class MyClass {
  public myMethod = thatMethod;
}
```

gives (note that `myMethod` is still defined, but `thatMethod` is not - giving an invalid d.ts file):

```
declare function myMethod(): string;
export default class MyClass {
	myMethod: typeof thatMethod;
}
```

Would you like this one in a separate issue? Apologies for finding them.

**Comment by timocov** [comment]
Using `* as NS`/`name as otherName` imports for _local modules_ (which should be inlined) doesn't work at the moment because it requires to wrap modules/variables and/or rename them, see https://github.com/timocov/dts-bundle-generator/issues/134.
