### ISSUE TITLE
Lose Method Doc comments when import() is used for types withh `removeComments` false

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#159]
**Bug report**
Lose doc comments in `index.d.ts` while run `npx dts-bundle-generator src/index.ts -o index.d.ts`
**Input code**
 [Please see demo example here](https://github.com/tianyingchun/dts-bundle-issue/tree/master)

**Expected output**

```ts
...
 /**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
	setDebugStatus: (options: FabricDebugOptions) => FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};
```

**Actual output**

```ts
....
 /**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
  /**
   * comments for method `setDebugStatus`
   * @param options 
   * @returns 
   */
 setDebugStatus: (options: FabricDebugOptions) => FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};
```

**Additional context**
"dts-bundle-generator": "^5.9.0",

**Comment by timocov** [comment]
@tianyingchun I think expected and actual results should be reversed right?

**Comment by timocov** [comment]
Actually the behavior looks correct - `setDebugStatus` from `fabricUtils` is not the same as the function `setDebugStatus` itself, if you'd like to have a JSDoc there you need to specify it explicitly.

**Comment by tianyingchun** [comment]
> @tianyingchun I think expected and actual results should be reversed right?

yes, should be reversed :)

**Comment by timocov** [comment]
Based on https://github.com/timocov/dts-bundle-generator/issues/159#issuecomment-846431281 I'm going to close the issue which is not a problem actually. If you'll have any updates, feel free to re-open it or post a comment.
