### ISSUE TITLE
Lose generic typings for function paramter and return types

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#160]
**Bug report**

[Full demo code is here] (https://github.com/tianyingchun/dts-bundle-issue/tree/master)

**Input code**
```ts
// set-debug.ts
import { Json } from './type.common';
import { FabricDebugCallbackData, FabricDebugOptions } from './type.debug';

/**
 * comments for method `setDebugStatus`
 * @param options 
 * @returns 
 */
export const setDebugStatus = <T extends Json,R extends Json>(options: FabricDebugOptions<T>): FabricDebugCallbackData<R> => {
  console.log('options', options)
  return {} as FabricDebugCallbackData<R>;
};

// type.common.ts
export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};

export declare type FabricCallbackData<T extends Json = null> = {

   code: "fabric_catched_error" | string;

   data: T;
}

//type.debug.ts
import { FabricCallbackData, Json } from './type.common';

export type FabricDebugOptions<T> = {
  enableDebug: T;
};


export type FabricDebugCallbackData<R extends Json> = FabricCallbackData<{
  enabled: R;
}>;

// index.ts
import { setDebugStatus } from './set-debug';

/**
 * comments for fabric utils.
 */
export const fabricUtils = {
  setDebugStatus,
};


 
```

**Expected output**

```ts
// Generated by dts-bundle-generator v5.9.0

export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};
export declare type FabricCallbackData<T extends Json = null> = {
	code: "fabric_catched_error" | string;
	data: T;
};
export declare type FabricDebugOptions<T> = {
	enableDebug: T;
};
export declare type FabricDebugCallbackData<R extends Json> = FabricCallbackData<{
	enabled: R;
}>;
/**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
	setDebugStatus: <T extends Json, R extends Json>(options: FabricDebugOptions<T>) => FabricDebugCallbackData<T>;
};
export declare const fabricX: () => string;

export {};

```

**Actual output**

```ts
// Generated by dts-bundle-generator v5.9.0

export declare type Json = undefined | null | boolean | number | string | Json[] | {
	[prop: string]: Json;
};
export declare type FabricCallbackData<T extends Json = null> = {
	code: "fabric_catched_error" | string;
	data: T;
};
export declare type FabricDebugOptions<T> = {
	enableDebug: T;
};
export declare type FabricDebugCallbackData<R extends Json> = FabricCallbackData<{
	enabled: R;
}>;
/**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
	setDebugStatus: <T extends Json, R extends Json>(options: FabricDebugOptions) => FabricDebugCallbackData;
};
export declare const fabricX: () => string;

export {};

```

**Additional context**
``` "dts-bundle-generator": "^5.9.0",```

**Comment by timocov** [comment]
Hi there, sorry for late reply.

It seems that the compiler generates such code https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEGcAsHsHcCiBbAlgFwLACgQQCYCmAxgDYCGATueqrAHYBco6lAroTnlHEmuukL4AYqlKFmqekQAeAOnxz0kHFzDgAZmML1yyCaEiF0AWiIAjNgHMlK7KmQAHWJXSgA3qABSkBqAC+oBqUsMigAORywOgAno6EcsShyAzhANw4Ds6uHqDC5OaUqMQAIoSWVgDC5KSk5uTEANYlNOQANHkFRaXl1gDyjrQMkAFBIWGR0XEJFtbpqrgAVIs4oIugScj69MpBLqD66HD4oAAGRuhlFQDK6DRskKer6+COVHqgsIN09CPPEJRjGxKL9QM9gDhCDJsm4kr83BcrtZbvcRgBeUAAHgAKqAoYJpCMfAw2gAlPEyAn4Im+egAPgAFF8hr9mPlCsUkVYBizIDi6QBKNldTm9Ko1OoNZqtTGkumgNHy9yrDbDWDiOSkWBWBnhZk-SDhDr64YClWA9DA+geQLkEbs7pc6q1epNFp3WV0jLYfzetQQLTiXT6ZixeKJZIMWyQ6EuNxEMhUQgsabeWkK0BsaSELT0ISgAA+oHobFqhdA5lg6sI5GtRZLyHMhEo5cgrCkVnLxPoAG0ALrl5XYACQPccIUczDbRXoVj7zG73t9CyhMNACYogJT8U6HOIzslbpluPxOmpab8GJLtXlGKHKtVRGYACINCLiAB9Yg0YjQIQf5sQkoZ9W3bWc-WwUAoPwVpmGxJcFm4QMdD0AwwxmMVo3sJw41yB1igPV1pTuDpu1GYJQgiKJ0IjLZUgg1dcPQ3dHTFHkDX5DMhyglDzHELk4KXCCYzXZj8J6CpCKld1yFlCkqRpBhbxYgiJSImTMW4vFdD4oRmFJJcvUQ9RkODAwpFkLCslwzxETFFFLRGQIKImKILjMMV5mwLhln+TZtl2DR9jfPdM1oUhIDkcERNwuE2yCd8AFVwvRDwVTsm47kctocGXbz8rBbAgA:

```ts
/**
 * comments for fabric utils.
 */
export declare const fabricUtils: {
    setDebugStatus: (options: import("./type.debug").FabricDebugOptions) => import("./type.debug").FabricDebugCallbackData;
};
```

I'm not sure whether it will work the same as from the source code though, at least it looks different.

**Comment by timocov** [comment]
As you can see the compiler strips a generic parameters at all so probably it's the issue of TypeScript compiler not this tool.

**Comment by tianyingchun** [comment]
yes, i agree you , for latest typescript it seems have this bug, have you submit bug report to `typescript` team? 💯

**Comment by timocov** [comment]
No, I don't. You can submit it and post a link here.
