### ISSUE TITLE
[Feature] Make it possible to bundle all the entries in a single file and remove the generated file

### ISSUE THREAD

**Issue by aryaroudi** [timocov/dts-bundle-generator#163]
I expected to have the possibility to bundle all the entry files into a single file but I see unfortunately it is not possible! so I don't understand the point of calling this package a `bundler`? it generates a single file for each entry, so the bundle ability is missing or something is wrong with my config?

Also, it would be great to have an option to remove the generated `d.ts` files after bundling them into a single one!

```
const config = {
    compilationOptions: {
        preferredConfigPath: './tsconfig.json',
    },

    entries: [
        {
            filePath: './src/constants/types.ts',
            output: commonOutputParams,
        },
        {
            filePath: './src/constants/classes.ts',
            output: commonOutputParams,
        },
    ],
};
```

**Comment by timocov** [comment]
@aryaroudi can I help you here somehow or the issue is solved now?
