### ISSUE TITLE
cannot process css

### ISSUE THREAD

**Issue by woutFrusch** [timocov/dts-bundle-generator#166]
I get the following error when using the generator: _TS2307: Cannot find module '' or its corresponding type declarations._ when I bundle a project containing at least one module which imports a css file.

When I run typescript (tsc) this error does not occur, I had to add a global.d.ts with declare module "*.css";

My question: can you bundle when there a css file? If so what am I doing wrong or is there a workaround?

I have used the generator in a project without css and it works great.

**Comment by timocov** [comment]
Can you create a repro for this please?

**Comment by woutFrusch** [comment]
yes, I commit it to github: https://github.com/woutFrusch/dts-test/

I used yarn as package manager

**Comment by timocov** [comment]
See https://github.com/timocov/dts-bundle-generator/issues/50#issuecomment-412668288. You need to put `/// <reference path="../../global.d.ts" />` to all files where you're going to use your "globals". Let me know if you'll have any further questions.
