### ISSUE TITLE
Generated .d.ts does not import destructure  react imports

### ISSUE THREAD

**Issue by chrishoage** [timocov/dts-bundle-generator#168]
**Bug report**

Below I have supplied a minimal repo. In our project we destructure react types in our files. The output of the bundle does not include these imports causing a malformed d.ts 

**Input code**

```ts
import React, { ReactElement } from 'react';

export function Test(): ReactElement {
  return <div />;
}

export const ForwardedRef = React.forwardRef<HTMLDivElement>((props, ref) => <div ref={ref} {...props} />)

```

**Expected output**

```tsx
// Generated by dts-bundle-generator v5.9.0

/// <reference types="prop-types" />
/// <reference types="react" />
/// <reference types="scheduler" />
import { ReactElement } from "react";

export declare function Test(): ReactElement;
export declare const ForwardedRef: React.ForwardRefExoticComponent<React.RefAttributes<HTMLDivElement>>;

export {};

```

**Actual output**

```ts
// Generated by dts-bundle-generator v5.9.0

/// <reference types="prop-types" />
/// <reference types="react" />
/// <reference types="scheduler" />

export declare function Test(): ReactElement;
export declare const ForwardedRef: React.ForwardRefExoticComponent<React.RefAttributes<HTMLDivElement>>;

export {};

```

**Additional context**
Add any other context about the problem here (CLI options, etc)

tsconfig.json
```jsonc
{
  "compilerOptions": {
    "jsx": "react",
    "lib": ["DOM", "ES2015", "ES2016"],
    "esModuleInterop": true,
    "skipLibCheck": true
  }
}
```

package.json
```json
{
  "dependencies": {
    "dts-bundle-generator": "^5.9.0",
    "react": "^17.0.2",
    "@types/react": "^17.0.19"
  }
}
```

### Command 

```
› dts-bundle-generator index.tsx -o index.d.ts
Compiling input files...
Processing index.tsx
Library "react" will be added via reference directive
Library "prop-types" will be added via reference directive
Library "scheduler" will be added via reference directive
Writing index.tsx -> index.d.ts
Checking generated files...
Compiler option "skipLibCheck" is disabled to properly check generated output
index.d.ts(7,33): error TS2304: Cannot find name 'ReactElement'.

Error: Compiled with errors

```

**Comment by timocov** [comment]
Hi @chrishoage,

sorry for late reply.

```ts
// Generated by dts-bundle-generator v5.9.0

/// <reference types="prop-types" />
/// <reference types="scheduler" />

import React from 'react';
import { ReactElement } from 'react';

export declare function Test(): ReactElement;
export declare const ForwardedRef: React.ForwardRefExoticComponent<React.RefAttributes<HTMLDivElement>>;

export {};

```

is this correct "expected" output for you? I just added `--external-imports react` to your command to get `./node_modules/.bin/dts-bundle-generator index.tsx -o index.d.ts --external-imports react` and it generates the code above, which looks correct for me, but I'm not sure whether it is good for you as well.

**Comment by chrishoage** [comment]
That is mostly correct. I do recall trying that previously and it caused other issues. Unfortunately I have left the company for who I originally opened this GHI for so no longer have access to the complex case to illustrate what issues external-imports caused.  

This section in the docs is what confused me

> By default all libraries will be imported (except inlined and libraries from `@types`)    

It wasn't clear to me why libraries from `@types` would not be imported. 

We were trying to switch away from rollup to esbuild and needed something to bundle our .d.ts for the library. In the end we kept using https://github.com/wessberg/rollup-plugin-ts only for the .d.ts files and use esbuild for the JS bundle. 

I obviously don't understand the architecture of this project, but I had expected to not need to specify external-imports. 

While I was at the company I tried every .d.ts bundle generator I could find (I got the furthest with your project), and in the end the only one that would actually produce a working .d.ts bundle was the project I linked above. 

If you would like please feel free to close this issue as I won't be able to further follow up with it.

**Comment by timocov** [comment]
> It wasn't clear to me why libraries from @types would not be imported.

> but I had expected to not need to specify external-imports.

I think that the reason was that some of packages which have types from `@types` don't export their API so they should be referenced as triple-slash directive types to load them (see old versions of jquery for instance, which wasn't a module back in days). For it was a long time ago, probably I need to change the default value for typing from `@types` to "should be imported #170.

> and in the end the only one that would actually produce a working .d.ts bundle was the project I linked above

Would be interesting to see what exactly didn't work though.

But anyway thanks for you report!

**Comment by igorpupkinable** [comment]
Thank you for the details.

Perhaps I need to rephrase my question.
`allowedTypesLibraries: ['react']` option will only work with `const HellowWorld: React.FC = () => null;` code.

My library has over 100 components with `FC` type instead of `React.FC`. So `importedLibraries: ['react']` is the only working solution otherwise you get `lib/index.d.ts(1,18): error TS2304: Cannot find name 'FC'.` error.
FC must be imported.

**Comment by timocov** [comment]
> allowedTypesLibraries: ['react'] option will only work with const HelloWorld: React.FC = () => null; code.

Yep, that's correct (and iirc this is the default behaviour for now right? I mean you don't need to even specify `allowedTypesLibraries` explicitly to achieve this, after #170 it will be changed).
