### ISSUE TITLE
error TS2304: Cannot find name 'SomeCustomType' while trying to use custom declarations for js modules with no types.

### ISSUE THREAD

**Issue by facinick** [timocov/dts-bundle-generator#169]
Hello,

I have a node typescript project, below is my tsconfig.json at the root of my project:

<tsconfig.json>
```
{
    "compilerOptions": {
        "incremental": true,
        "target": "es2017",
        "outDir": "dist",
        "rootDir": "src",
        "moduleResolution": "node",
        "module": "commonjs",
        "declaration": true,
        "declarationDir": "./types",
        "declarationMap": true,
        "inlineSourceMap": true,
        "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
        "resolveJsonModule": true /* Include modules imported with .json extension. */,
        /* Additional Checks */
        "noUnusedLocals": true /* Report errors on unused locals. */,
        "noUnusedParameters": true /* Report errors on unused parameters. */,
        "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
        "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,
        /* Debugging Options */
        "traceResolution": false /* Report module resolution log messages. */,
        "listEmittedFiles": false /* Print names of generated files part of the compilation. */,
        "listFiles": false /* Print names of files part of the compilation. */,
        "pretty": true /* Stylize errors and messages using color and context. */,
        "lib": ["es2015", "DOM"],
        "types": ["node"],
        "typeRoots": ["node_modules/@types", "src/types"]
    },
    "include": ["src/**/*.ts", "types/self_delarations.d.ts"],
    "exclude": ["node_modules/**"],
    "compileOnSave": true
}
```

I have exported all declaration files and their maps in `types` folder which is at the root of my project

As you can see I've added a file (`types/self_delarations.d.ts`) in include array in the above config. this file has types that I add for imported js libraries with no types of their own. here is the contents of self_declarations.d.ts:

<self_delarations.d.ts>

```
declare module 'my-awesome-js-library' {
    type SomeCustomType = string | boolean;
    const someFunction: () => SomeCustomType;

    export { someFunction, SomeCustomType };
    export default someFunction;
}
```

The library has one index.js file with the following content:

<node_modules/my-awesome-js-library/index.js>
```
function someFunction() { return false };

try {
	module.exports = someFunction;
} catch (e) {
	String.someFunction = someFunction;
}
```

I am consuming this library just fine in my project.

However, I am using dts-bundle-generator as a post build process by running:

`dts-bundle-generator -o ./dist/bundle.d.ts ./types/index.d.ts`

this tries to generate bundle.d.ts in my dist folder, and generates the following content :

`export declare const data2: SomeCustomType;
`

and this is causing an error: `dist/bundle.d.ts(1,29): error TS2304: Cannot find name 'SomeCustomType'.`

How can I resolve this issue? I want to be able to add custom types in my types/self_declarations.d.ts file for modules that don't have their own types.

**Comment by timocov** [comment]
Hi @facinick, could you provide minimal repro for the issue please?

**Comment by facinick** [comment]
@timocov , could you please check the question above, I've added code with filename that's enough to cause the problem, I don't know what else to provide

**Comment by facinick** [comment]
----------------- FOLDER STRUCTURE ---------------------

node_modules
src
.... types
.... .... self_declarations.d.ts
.... index.ts
package.json
tsconfig.json

--------------------------- CODE ---------------------------

**<src/types/self_declarations.d.ts>**
```
declare module 'my-awesome-js-library' {
    type SomeCustomType = string | boolean;
    const someFunction: () => SomeCustomType;

    export { someFunction, SomeCustomType };
    export default someFunction;
}
```

**<src/index.ts>**
```
import {someFunction} from 'my-awesome-js-library';
someFunction();
```

**<tsconfig.json>** 
```
{
    "compilerOptions": {
        "incremental": true,
        "target": "es2017",
        "outDir": "dist",
        "rootDir": "src",
        "moduleResolution": "node",
        "module": "commonjs",
        "declaration": true,
        "declarationDir": "./types",
        "declarationMap": true,
        "inlineSourceMap": true,
        "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
        "listEmittedFiles": false /* Print names of generated files part of the compilation. */,
        "listFiles": false /* Print names of files part of the compilation. */,
        "lib": ["es2015", "DOM"],
        "types": ["node"],
        "typeRoots": ["node_modules/@types", "src/types"]
    },
    "include": ["src/**/*.ts", "types/self_delarations.d.ts"],
    "exclude": ["node_modules/**"],
}
```
---------------------DTS GENERATION STEP -------------------------

`dts-bundle-generator -o ./dist/bundle.d.ts ./types/index.d.ts`

------------------ DTS GENERATOR OUTPUT FILE ----------------------
**<dist/bundle.d.ts>**
```
...
export declare const data2: SomeCustomType;
...
```

-------------------------- ISSUE ---------------------------
Error: dist/bundle.d.ts(1,29): error TS2304: Cannot find name 'SomeCustomType'.

**Comment by facinick** [comment]
@timocov , this might help better ^^

**Comment by timocov** [comment]
@facinick sorry for late reply. As I can see from your code, you declared a types for a package that doesn't have types in npm, right? What would you expect to have in the result here? Should `declare module 'my-awesome-js-library'` be inlined in your result bundle? Or maybe you'd expect to have only import statement from `my-awesome-js-library` package (but in this case, since this library doesn't have types, it might break others build)? Maybe something else?

**Comment by superdc** [comment]
I have the same problem。I have a component imported from @base/components which is not a npm package
```
import { EnvSelect } from '@base/components'
```
It has custom declaration in module.d.ts
```
declare module '@base/components' {
  export const EnvSelect: (props: any) => JSX.Element
}
```
but when I use dts-bundle-generator, it has errors: Cannot find module '@base/components' or its corresponding type declarations. I want to know how to fix this error.

**Comment by timocov** [comment]
> but when I use dts-bundle-generator, it has errors: Cannot find module '@base/components' or its corresponding type declarations. I want to know how to fix this error.

@superdc could you provide a repro for your case?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.

**Comment by Rush** [comment]
I have a similar issue. I understand a minimal repro is needed. If I don't find a solution I'll try to create one but it may be difficult for more complex projects. I understand it may be difficult to guess what's wrong without a repro. Anyhow, FYI!
