### ISSUE TITLE
`export default Name;` is not handled correctly

### ISSUE THREAD

**Issue by timocov** [timocov/dts-bundle-generator#17]
**Code:**
```ts
class MyClass {}
export default MyClass;
```

**Actual output:**
```ts
export declare class MyClass {
}
export default MyClass;
```

**Expected output:**
```ts
declare class MyClass {
}
export default MyClass;
```

**Comment by bigopon** [comment]
@timocov Hi, has there been any progress related to this?

**Comment by timocov** [comment]
Unfortunately not yet 🙁.

I'm working on the next version https://github.com/timocov/dts-bundle-generator/milestone/4 - let's try to fix this issue within this version.

**Comment by timocov** [comment]
Hi @bigopon. I just created PR #61 with fixes for this issue. If you can test it for your case it would be awesome!

**Comment by bigopon** [comment]
Cool, will give it a shot soon. Thanks @timocov
