### ISSUE TITLE
Should dts configuration need to support ignore @types/a, @types/b .... pckages.

### ISSUE THREAD

**Issue by tianyingchun** [timocov/dts-bundle-generator#174]
**Bug report**
Should dts configuration need to support ignore @types/a, @types/b .... pckages.

in some case, maybe @types/* package has some typings issues here  and our project don't dependent these issued packages, we can ignore it while `dts-genereate-bundle` initialize.

now if @types/* has any of issue typing package, the `dts-bundle-generator` is break down.
**Input code**

```ts
// place your code here
```

**Expected output**
provider us configuration like `allowedTypesLibraries` definitions, `dts-bundle-generator` ignore it before bundling...

```ts
// place your code here
```

**Actual output**

```ts
// place your code here
```

**Additional context**
Add any other context about the problem here (CLI options, etc)

**Comment by timocov** [comment]
Could you provide an example please? I'm not sure that understood your issue

**Comment by tianyingchun** [comment]
e.g.  i run cli `dts-bundle-generator` it will throw me below errors
```
Error: Cannot find symbol for node: ChainExpression
  Error: Command failed with exit code 1: /Users/tianyingchun/Documents/coding/kzfoo/kzfoo-admin/node_modules/dts-bundle-generator/dist/bin/dts-bundle-generator.js -config=flatjs.dts.js -silent=true
```
BUT it caused by `node_modules/@types/eslint, eslint-scope,estree` has typings errors.

![image](https://user-images.githubusercontent.com/2833251/141458557-96ec49db-a6f0-4459-81a8-275bfa5a0731.png)

in fact in my `project` it will not use `@types/eslint, eslint-scope,estree` to bundle typings dependencies.

Resolttion: 

mannully delete packages `node_modules/@types/eslint, eslint-scope,estree` the `dts-bundle-generator` works fine.

i means `dts-bundle-genderator` provider us options to ignore Unnecessary dependencies, Rather than import all typings packages from `typeRoot` `node_mdules/@types/*` into runtime

**Comment by timocov** [comment]
Afaik by default TypeScript will load all types to the program from `@types` folder. Have you tried to change https://www.typescriptlang.org/tsconfig#types compiler option to declare there only needed "global" types (if all types are modules you can set it to an empty array - in this case TypeScript will load only imported types).

**Comment by tianyingchun** [comment]
thanks very must point this, it make sense.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
