### ISSUE TITLE
Extended interfaces from inlined externals are not picked up

### ISSUE THREAD

**Issue by manwithafox** [timocov/dts-bundle-generator#186]
**Bug report**

**Input code**
_src/index.ts_:
```ts
import {IDerived} from 'reuse-me';

export class X implements IDerived {
    public id: string;
    public name: string;
}
```

_typings/reuse-me/index.d.ts_:
```ts
declare module 'reuse-me' {

    export interface IBase {
        id: string;
    }

    export interface IDerived extends IBase {
        name: string;
    }
}
```

See [demo repo](https://github.com/manwithafox/demo-export-extended-interfaces)

(Exported) [base interface](https://github.com/manwithafox/demo-export-extended-interfaces/blob/d65062175047433035fba0dea13eb627c5fb3781/typings/reuse-me/index.d.ts#L3-L5) is not included in [final d.ts](https://github.com/manwithafox/demo-export-extended-interfaces/blob/d65062175047433035fba0dea13eb627c5fb3781/foo.d.ts#L7)

**Expected output**

```ts
// Generated by dts-bundle-generator v6.4.0

export interface IBase {
	id: string;
}

export declare class X implements IDerived {
	id: string;
	name: string;
}
export interface IDerived extends IBase {
	name: string;
}

export {};
```
included in d.ts

**Actual output**

```ts
// Generated by dts-bundle-generator v6.4.0

export declare class X implements IDerived {
	id: string;
	name: string;
}
export interface IDerived extends IBase {
	name: string;
}

export {};
```
(**IBase not included**)

**Additional context**

Command-line used to generate:
`npx dts-bundle-generator -o foo.d.ts src/index.ts --project tsconfig.json --external-inlines reuse-me`

**Comment by timocov** [comment]
Fixed in https://github.com/timocov/dts-bundle-generator/releases/tag/v6.5.0
