### ISSUE TITLE
How to use in gulp?

### ISSUE THREAD

**Issue by keyiis** [timocov/dts-bundle-generator#188]
I want use dts-bundle-generator in gulp,but not work.
```
require('dts-bundle-generator').generateDtsBundle([
        {
            "filePath": `${PROJECT_PATH}/index.ts`,
            "outFile": `${DIST_PATH}/index.d.ts`
        }
    ],{
        preferredConfigPath:'tsconfig.json'
    });
```
nothing happen,no output,no error

**Comment by timocov** [comment]
Please note that `outFile` option exists in [the config file only](https://github.com/timocov/dts-bundle-generator/blob/ac4e0e56b9030f0542ed6632e86231e3c82d0f1b/src/config-file/load-config-file.ts#L9-L13) (i.e. by using from the CLI) and it doesn't exist if you're using `generateDtsBundle`. In this case [this function will return you an array of content strings](https://github.com/timocov/dts-bundle-generator/blob/ac4e0e56b9030f0542ed6632e86231e3c82d0f1b/src/bundle-generator.ts#L136) that you can write to the file system (or whatever you want to).
