### ISSUE TITLE
How to use it with webpack?

### ISSUE THREAD

**Issue by euberdeveloper** [timocov/dts-bundle-generator#191]
Is there an already made webpack plugin or something?

**Comment by timocov** [comment]
I think you can fine some [here](https://www.npmjs.com/package/dts-bundle-generator):

![image](https://user-images.githubusercontent.com/3112183/161389659-74137ca6-490d-43dd-bc72-1b271533348e.png)

https://www.npmjs.com/browse/depended/dts-bundle-generator
