### ISSUE TITLE
Incorrect re-export statements while using `paths` compiler option

### ISSUE THREAD

**Issue by euberdeveloper** [timocov/dts-bundle-generator#193]
**Bug report**

I am using custom paths such as `@/types` and the output .d.ts works, but has some lines that could be removed 

**Input code**

This is the `main.ts`

```ts
export * from '@/types';
export { GifAnalyzer } from '@/utils/analyzer';
```
And this is the `/types/index.ts`:

```ts
export * from './constants';
```

And this is the `/types/constants.ts`:

```ts
export enum GifVersion {
    V_87A = '87a',
    V_89A = '89a'
}

export const EXTENSION_INTRODUCER = 0x21;
export const TRAILER = 0x3b;

export enum ExtensionLabel {
    GRAPHIC_CONTROL_EXTENSION = 0xf9,
    COMMENT_EXTENSION = 0xfe,
    PLAINTEXT_EXTENSION = 0x01,
    APPLICATION_EXTENSION = 0xff,
    IMAGE_SEPARATOR = 0x2c
}
```

I omit the files relative to the utils, the situation is similar

**Expected output**

This is just the expected output relative to the `@/types` part

```ts
// [...]

export declare const EXTENSION_INTRODUCER = 33;
export declare const TRAILER = 59;
export declare enum ExtensionLabel {
	GRAPHIC_CONTROL_EXTENSION = 249,
	COMMENT_EXTENSION = 254,
	PLAINTEXT_EXTENSION = 1,
	APPLICATION_EXTENSION = 255,
	IMAGE_SEPARATOR = 44
}
export declare enum GifVersion {
	V_87A = "87a",
	V_89A = "89a"
}

// [....]
```

**Actual output**

In the actual output I have also this line: `export * from "@/types";`

```ts
// [...]
export * from "@/types";

// [...]

export declare const EXTENSION_INTRODUCER = 33;
export declare const TRAILER = 59;
export declare enum ExtensionLabel {
	GRAPHIC_CONTROL_EXTENSION = 249,
	COMMENT_EXTENSION = 254,
	PLAINTEXT_EXTENSION = 1,
	APPLICATION_EXTENSION = 255,
	IMAGE_SEPARATOR = 44
}
export declare enum GifVersion {
	V_87A = "87a",
	V_89A = "89a"
}

// [...]

```

**Additional context**

To full reproduce this problem, you can download this [snapshot of my repo](https://github.com/euberdeveloper/gif-analyzer/tree/d49cf265a75c93dcf8c0fc3cce05ab2f712aee7c), install the deps (`npm i`) and bundle the code (`npm run bundle`). You will have the output in `bundled/index.d.ts`

**Comment by euberdeveloper** [comment]
**Update**:

It actually creates problem, if I have the flag **skipLibCheck** set to false in the `tsconfig.json`, I get the following error because of that in a TypeScript program using that as a dependency:

![image](https://user-images.githubusercontent.com/33126163/161451539-e3d4eb01-a41b-458f-a8fa-6474e0eebf45.png)

(Note that @/classes is due to part of the code that I hid in the previous explaination)

**Comment by timocov** [comment]
Hi @euberdeveloper, is it possible to create a repo with the repro of the issue? Looks like [the provided link](https://github.com/euberdeveloper/gif-analyzer/tree/d49cf265a75c93dcf8c0fc3cce05ab2f712aee7c) doesn't work any more (or it is for the private repo? 🤔)

**Comment by euberdeveloper** [comment]
Sorry, now it's public

**Comment by timocov** [comment]
Thanks @euberdeveloper! It's a bug, I'll fix it soon.

**Comment by timocov** [comment]
@euberdeveloper it looks like you're using `bundle-declarations-webpack-plugin` package that didn't update its `dts-bundle-generator` dependency to the next major version yet ([it is using v5 so far](https://github.com/dominicbirch/bundle-declarations-webpack-plugin/blob/87da9dc1cee68800f1aee575cd303cbd3fdc5022/package.json#L31)) so probably you'll need to deal with it later. The fix will be available in v6.7.0 soon (see #194)

**Comment by euberdeveloper** [comment]
Ok thanks, maybe I will open an issue there and if he does not respond I'll fork it.

At this point, why don't you create an "official" webpack plugin yourself? It would be probably updated very soon (if the already existing are still maintained at all)

**Comment by timocov** [comment]
The new version v6.7.0 was released just now with a fix.

**Comment by timocov** [comment]
> why don't you create an "official" webpack plugin yourself?

@euberdeveloper Good question, I think there were a few reasons initially:
- I wanted to keep the package free from unnecessary dependencies (in case of proving a webpack plugin I would need to add `webpack` to the deps list in some way)
- Otherwise the repo would need to switch to monorepo and provide plugins for other bundlers/tools as well and maintain them every time (not just update the version) and to be honest I don't think that I'd want to do this, just because I have no experience with that and it will take time to monitor all the changes in bundlers to make sure that I don't use outdated/deprecated/removed API and so on. I'd delegate it to someone else who has such experience and is ready to maintain such package.

**Comment by euberdeveloper** [comment]
Now it's public

Il mer 6 apr 2022, 21:45 Evgeniy Timokhov ***@***.***> ha
scritto:
