### ISSUE TITLE
Possible to skipLibCheck while still checking final output?

### ISSUE THREAD

**Issue by wKovacs64** [timocov/dts-bundle-generator#195]
Hi, and thanks for your work on dts-bundle-generator!

I am converting a Node project from Jest to Vitest and dts-bundle-generator is complaining about missing types for a transitive dependency. `vitest` installs `jsdom` which installs `ws`, and `@types/ws` are not included, so `ws` is of type `any`. I can fix it by installing `@types/ws` in my project, but I'd prefer an alternative since that package really has nothing to do with my project. Using `--no-check` works, but that feels somewhat unsafe (or at least, not quite as robust/safe as it is now). Thoughts?

(Note: none of the above ever make it into my bundled types, so I'm not sure why it's tripping up the check.)

```
> dts-bundle-generator --silent --umd-module-name my-project --out-file dist/my-project.d.ts src/my-project.ts

node_modules/vite/dist/node/index.d.ts(51,47): error TS7016: Could not find a declaration file for module 'ws'. 'C:/projects/my-project/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
node_modules/vite/dist/node/index.d.ts(52,54): error TS7016: Could not find a declaration file for module 'ws'. 'C:/projects/my-project/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
Error: Compiled with errors
```

**Comment by timocov** [comment]
Hi @wKovacs64,

I'm just curious how does it work with your project? Does it compile successfully? Do you have this flag `skipLibCheck` enabled locally? It looks like it should fail with your code in the first place.

> but that feels somewhat unsafe (or at least, not quite as robust/safe as it is now). Thoughts?

> Possible to skipLibCheck while still checking final output? 

If you refer to [the documentation of `skipLibCheck` option](https://www.typescriptlang.org/tsconfig/#skipLibCheck) you will see the following:

> Skip type checking of declaration files.

So this option does exactly what `--no-check` flag does.

**Comment by wKovacs64** [comment]
> Does it compile successfully?

The project compiles (and passes tsc type checking) just fine but dts-bundle-generator errors (because it can't find types for the `ws` transitive dev dependency) unless I enable `--no-check`.

> Do you have this flag skipLibCheck enabled locally?

Yes.

> If you refer to [the documentation of skipLibCheck option](https://www.typescriptlang.org/tsconfig/#skipLibCheck)
> ...
> So this option does exactly what --no-check flag does

Hmm, I was under the impression enabling `skipLibCheck` would limit type checking to code specifically referred to in the project's source (so in this case, it would ignore any `ws` stuff since I don't use it) while `--no-check` would skip validation of the final generated type bundle. Those seem like different things to me? But maybe I just misunderstand.

**Comment by timocov** [comment]
@wKovacs64 Ah wait, I see what you mean. I misunderstood you, my bad.

It looks [the only place](https://github.com/timocov/dts-bundle-generator/search?q=skipLibCheck&type=code) that uses `skipLibCheck` flag is for [checking the result `d.ts` file only](https://github.com/timocov/dts-bundle-generator/blob/a0cb4e4e8332f95ad2cce232ccaca1c07064e6f5/src/bin/dts-bundle-generator.ts#L252-L261) so the tool shouldn't disable it automatically unless it wants to check the result file. Do you have any specific issues? Maybe you load a wrong config file? Do you have steps to reproduce the issue?

**Comment by wKovacs64** [comment]
> It looks [the only place](https://github.com/timocov/dts-bundle-generator/search?q=skipLibCheck&type=code) that uses `skipLibCheck` flag is for [checking the result `d.ts` file only](https://github.com/timocov/dts-bundle-generator/blob/a0cb4e4e8332f95ad2cce232ccaca1c07064e6f5/src/bin/dts-bundle-generator.ts#L252-L261) so the tool shouldn't disable it automatically unless it wants to check the result file.

"unless it wants to check the result file" - this is the default behavior of dts-bundle-generator, correct? `--no-check` disables this? That's the problem, I believe. I _do_ want to check the resulting types bundle, but I _don't_ want to force `skipLibCheck` to `false` (due to missing types deep in node_modules that I don't really control). Doesn't look like that's currently possible, though.

> Do you have any specific issues? 

The specific issue is that dts-bundle-generator fails after installing a dev dependency that installs other dependencies without types (see error above).

> Maybe you load a wrong config file?

Not that I can tell, but I suppose it's possible.

> Do you have steps to reproduce the issue?

1. Working project (build and dts-bundle-generator) with jest in devDependencies (`skipLibCheck: true`)
2. Uninstall `jest` and `@types/jest`, install `vitest`
3. Build still works, but dts-bundle-generator fails
4. Add `--no-check`, dts-bundle-generator succeeds

**Comment by timocov** [comment]
> I do want to check the resulting types bundle, but I don't want to force skipLibCheck to false (due to missing types deep in node_modules that I don't really control)

But this makes no sense. From my experience the compiler won't check anything in the result `d.ts` because this option explicitly says "Skip type checking of declaration files.". Is there anything specific you think it might check though? From what I've observed the compiler just replaces a module with `d.ts` (not just node_modules, but _any_ `d.ts` file) file with kind of `any` type.

**Comment by timocov** [comment]
[Workbench example](https://www.typescriptlang.org/dev/bug-workbench/?skipLibCheck=true&ts=4.6.2#code/PTAEAEGcGsEsAcAysBGBhAFgUwMbQFygAuATgK5YBQlIEAZrADZYB2AhgLZaEDmjA9ijaMAjADoAJmKKRKE3IzYksoHPxaQioSG0gTCuibtABeUAG9QAXwDc1WuAbN2XQhzawW02Wo39mYgI8ABQ6egCUQA):

![image](https://user-images.githubusercontent.com/3112183/162631935-2b09d3ba-03c3-4115-92e5-b9178ac715c4.png)

![image](https://user-images.githubusercontent.com/3112183/162631943-21e5d65a-1eae-4920-9de3-ecb0cae11ae7.png)

As you can see there this options hides lots of errors and even if a file has incorrect syntax for `d.ts` file it won't raise any error.

**Comment by wKovacs64** [comment]
Yep, you're right - that was the point of confusion. I was always under the impression `skipLibCheck` only applied to `node_modules` for some reason. 🤯 (I think because at one point, it was recommended as a solution if some types out of your control were incorrect or conflicting.) Well... now I need to go rethink my life. Sorry for the noise, and thanks for walking through it with me.

**Comment by timocov** [comment]
No worries that's alright 😂 I understand your feeling - I was thinking exactly the same previously and I was quite surprised that it works in this way.

Btw this is exactly why I would never suggest to use this option - it might hide some important errors if you're relying on the compiler a lot (and its type system/errors).

**Comment by bigopon** [comment]
I'm having some problem related @types/node @types/bun etc automatically getting pulled into the check for my build output, and I'm not sure how to solve this. Even with `typeAcquisition` disabled in main `tsconfig.json` it somehow still manages to check.
Does this ring any bell, or should I provide a repro?

**Comment by timocov** [comment]
For anyone getting into this thread - from [the compiler docs](https://www.typescriptlang.org/tsconfig/#skipLibCheck):

> Skip Lib Check - skipLibCheck
> Skip type checking of declaration files.

Basically this means "if skipLibCheck is enabled, then there is NO type check that are applied to the output file(s) because the output files ARE declaration files in their nature", meaning that most likely it is equal to "--no-check" flag provided (unless there is a syntax error probably). At least this is my understanding and interpretation, happy to be proven otherwise.
