### ISSUE TITLE
Inlined imports do not contain `import` statement from dependencies

### ISSUE THREAD

**Issue by nsamsonov** [timocov/dts-bundle-generator#199]
**Bug report**
I have my file and two libraries (`libA` and `libB`). `libA` imports some stuff from `libB`. I want `libA` to be inlined, while keeping import statements from `libB`.

**Input code**

myFile.ts
```ts
import { InlinedType } from "libA";

export interface MyType {
    prop: InlinedType;
}
```

node_modules/libA/index.d.ts
```ts
import { ImportedType } from 'libB';

export interface InlinedType {
    prop: ImportedType;
}
```

node_modules/libB/index.d.ts
```ts
export interface ImportedType {
    prop: number;
}
```

**Expected output**

```ts
import { ImportedType } from 'libB';

export interface InlinedType {
    prop: ImportedType;
}

export interface MyType {
    prop: InlinedType;
}
```

**Actual output**

```ts
export interface InlinedType {
    prop: ImportedType;
}

export interface MyType {
    prop: InlinedType;
}
```

**Additional context**
The import is generated using `dts-bundle-generator --external-inlines=libA myFile.ts`
Since the import statement is missing, the generated code is invalid. Adding `--external-inlines=libB` correctly inlines `libB`, but this is undesired behavior. Adding `--external-imports=libB` has no effect.

**Comment by nsamsonov** [comment]
It appears this is happening because of these lines:
https://github.com/timocov/dts-bundle-generator/blob/9676b66b7a693fcad1b99bf114cb6a6786876b36/src/bundle-generator.ts#L776-L778

Even though the declaration will eventually be inlined, it's still considered a part of the external lib

**Comment by timocov** [comment]
@nsamsonov have you tried a previous versions? I guess it could be broken in one of the recent versions...

**Comment by timocov** [comment]
@nsamsonov got it, thanks! I'll try to fix soon.

**Comment by timocov** [comment]
@nsamsonov the fix has been published in https://github.com/timocov/dts-bundle-generator/releases/tag/v6.9.0

**Comment by nsamsonov** [comment]
thanks a lot, it works great!
