### ISSUE TITLE
If I reference an external library, can I combine the external libraries together into one d.ts file?

### ISSUE THREAD

**Issue by phaethon5882** [timocov/dts-bundle-generator#202]
Hi, I'm trying to bundle declaration file which import external library.
such as,
```typescript
// this is declaration file which located in ./node_modules/@playwright/test/index.d.ts.
export * from 'playwright-core'; // <- located in ./node_modules/playwright-core/index.d.ts.
export * from './types/test';
export { default } from './types/test';
```
for bundle declaration file of '@playwrigh/test', i tried below,
`dts-bundle-generator -o playwright-test.d.ts --external-inlines=playwright-core ./node_modules/@playwright/test/index.d.ts`

but, i got the ouput like below,
```typescript
// Generated by dts-bundle-generator v6.9.0

...(playwright-core declarations work very well!)...
// but, ./types/test (relative path) isn't inline correctly...
export * from "./types/test";
export { default } from "./types/test";

export {};
```

Could you please tell me how to properly merge external libraries in this situation?

**Comment by timocov** [comment]
@phaethon5882 it seems that you're trying to bundle a package from node_modules folder. If you want to inline everything from this package you need to declare that explicitly in `external-inlines` option. In your case, for "current folder" (or for you project's folder) `@playwright/test` is a separate package and if you want to inline everything from it into "your package" (in terms of a current folder or a folder of running or a project) you need to specify this "external" as well. Thus, try to specify both packages: `--external-inlines=playwright-core @playwright/test` (or similar). I hope this helps.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
