### ISSUE TITLE
feature request: generated declaration files import types from each other

### ISSUE THREAD

**Issue by samualtnorman** [timocov/dts-bundle-generator#211]
hi sorry me again,

I'd like the ability to have generated declaration files import types from each other rather than having the same type inlined multiple times across multiple declaration files

I will once again once again have a go at implementing this myself if this is a feature worth having

thanks again for reading this :D

**Comment by timocov** [comment]
I believe this is exactly what we have in #69. This is nice to have feature for sure, but the solution is kind of trick and could be a far away from a "straightforward" one though.
