### ISSUE TITLE
feature request: generate single `.d.ts` file

### ISSUE THREAD

**Issue by samualtnorman** [timocov/dts-bundle-generator#212]
hi

this is a feature from [`npm-dts`](https://github.com/vytenisu/npm-dts) where it takes multiple declaration files and merges them into a single declaration file using `declare module`

sorry for pestering you with 3 issues in quick succession but this is the last one (for now :))

thanks :D

**Comment by timocov** [comment]
So what's do you expect to have here exactly? Do the same job that npm-dts does? Or something else? Not sure that got it correctly.

**Comment by samualtnorman** [comment]
I imagine the way it would be used is, you use the command as normal to generate declarations for your entries, but with the option specified, rather than emitting multiple declaration files, it just generates the one

**Comment by timocov** [comment]
@samualtnorman can you provide a use case for that? when it might be useful and what this might solve?

**Comment by samualtnorman** [comment]
it's not really solving an issue
it's definitely just a nice to have
my use case is that I'd use it to publish just 1 declaration file rather than 1 for each entry which in the case of a library would double the amount of files your publishing

**Comment by timocov** [comment]
> my use case is that I'd use it to publish just 1 declaration file rather than 1 for each entry which in the case of a library would double the amount of files you're publishing

What amount of files are we talking about? I'd consider to implement code-splitting feature rather than this tbh, because the value of this isn't too clear at least for me.

**Comment by samualtnorman** [comment]
what do you mean by code splitting in this case? what does that solve?

**Comment by timocov** [comment]
Ah sorry, I misinterpret your goal and thought that you want to reduce the amount of nodes you'd want to ship to reduce the compilation time for dependant projects.

What amount of files are we talking about? Is it more than let's say 10-20? If is not that much, I'd say it is nothing for the compiler and probably even better, because a consumer won't load the files they don't need at the moment.

I'm still trying to understand the value of this feature rather than "you'd like to have it because you don't like many files" 😄

**Comment by samualtnorman** [comment]
I didn't mean to say what you were suggesting wouldn't work
I meant to ask how what you were suggesting would help
it's unfortunate that the english language still makes the above sentence sound as if I'm doubting you

**Comment by timocov** [comment]
No worries, that's alright. The reason why I have doubts on this feature request is that I don't really see the value of having this. From the consumer's side it could be easily done by reading files, concatenating them together with `declare module 'name' {` prefix to each file (from my understanding), so you don't even need to have a knowledge of the typescript or the compiler. And what I wanted to know is what problems this might solve or what advantages it might give you as a consumer. At the moment I don't see any, unfortunately. Having a feature that makes no sense looks like having a dead code that no one uses but it is here "just for fun" or so.

Thus I'm going to close the issue, but if you'll have any updates/ideas/thoughts on this and the purpose - just let me know by replying to this issue.
