### ISSUE TITLE
jsdoc typedef {import('').Mod} Mod overwrite the real Mod type

### ISSUE THREAD

**Issue by easyfrog** [timocov/dts-bundle-generator#226]
**Bug report**

**Input code**

```ts
// place your code here

// I use this line to get types of Map class
/** @typedef {import("../core/Map").Map} Map */

// after bundle it will be like this
export type Map = Map;

// BUT it will overwrite my real Map class type
```

**Expected output**

```ts
// place your code here

// JUST ignore /** @typedef {import("../core/Map").Map} Map */ in the bundler

```

**Actual output**

```ts
// place your code here
export type Map = Map;
```

**Additional context**
Add any other context about the problem here (CLI options, etc)

**Comment by timocov** [comment]
@easyfrog can you create a complete repro please? The bundle doesn't add anything to types, only uses what the compiler produces during the compilation so likely its is the output of the compiler. But to say for sure I need to have a full repro.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any update - feel free to ping me.
