### ISSUE TITLE
custom type.d.ts: files that are using custom declaration types are not generating d.ts files

### ISSUE THREAD

**Issue by aibrahim3546** [timocov/dts-bundle-generator#227]
I have my own npm package which use styled-components. So to define the type for the theme, I need to create `styled.d.ts` files. I am using a `useTheme` hook provided by the `styled-components` library.

During development it's working perfect. It is giving me the auto suggestions.

**The Problem**
I have two files. File A and file B.

File A are not using the `useTheme` function. When I run the command to build the declaration file for File A. It's **working** as expected.

File B are consuming the `useTheme` function. When I run the command to build the declaration file for File B. It is **not working**. It's not creating the d.ts file.

command I am using: `-o <dtsPath> <entryPath> --no-banner`

**Comment by timocov** [comment]
Can you provide a repro for your issue?

**Comment by aibrahim3546** [comment]
**fileA.tsx**
```
// src/fileA.tsx

import { useTheme } from 'styled-components'

const ComponentA = () => {
  const theme = useTheme()
  const color = theme.primary

  return (...)
}

export default ComponentA
```

**src/typings/styled.d.ts**
```
import 'styled-components'

declare module 'styled-components' {
  export interface DefaultTheme {
    primary: string
  }
}
```

**src/fileB.tsx** not using the `useTheme`
```
// fileB.tsx

const ComponentB = () => {
  return (...)
}

export default ComponentB
```

---

run command on fileA: `dts-bundle-generator -o src/fileA.d.ts src/fileA.tsx --no-banner --external-imports=styled-components`

When running the command above the `fileA.d.ts` is not being generated

run command on fileB: `dts-bundle-generator -o src/fileB.d.ts src/fileB.tsx --no-banner --external-imports=styled-components`

When running the same command for **fileB.tsx** it works.

**Comment by timocov** [comment]
See my explanation of similar problem here https://github.com/timocov/dts-bundle-generator/issues/102. tldr: you have to add `src/typings/styled.d.ts` file into the compilation either by using triple-slash directive or importing them explicitly. Also see https://github.com/timocov/dts-bundle-generator/issues/203
