### ISSUE TITLE
`--external-inlines` doesn't bundle completely

### ISSUE THREAD

**Issue by pofulu** [timocov/dts-bundle-generator#234]
**Bug report**

The `--external-inlines` not bundle all used types.

**Input code**

```ts
import { Subject } from "rxjs";

const subject = new Subject<void>();

// This should return `Observable<void>
export function onEvent() {  
  return subject.asObservable();
}
```

**Expected output**

The `Observable<void>` should be inlined, no need to import `rxjs` package.

```ts
// ...All inline types
export declare function onEvent(): Observable<void>;
export {};
```

**Actual output**

 But `Observable` still not be inlined, and need to import `rxjs` package.

```ts
// ...All inline types
export declare function onEvent(): import("rxjs").Observable<void>;
export {};
```

**Additional context**

I use the following command to bundle:

```shell
pnpm dts-bundle-generator ./src/app.ts --external-inlines 'rxjs'
```

**Comment by timocov** [comment]
@pofulu thanks for reporting! The fix has been released in [v7.2.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v7.2.0)
