### ISSUE TITLE
Add handling `export =` for namespaces 

### ISSUE THREAD

**Issue by e2tox** [timocov/dts-bundle-generator#24]
dts-bundle-generator@1.1.0

to reproduce

```bash
git clone https://github.com/e2tox/reproduce-dts-bundle-generator-node-imports.git
cd reproduce-dts-bundle-generator-node-imports
npm install
npm test
```

Error details:
```bash
> dts-bundle-generator -o ./index.d.ts ./stoppable.d.ts

Writing generated file to ./index.d.ts...
Checking the generated file...
index.d.ts(1,52): TS2304: Cannot find name 'EventEmitter'.
Error: Compiled with errors
npm ERR! Test failed.  See above for more details.

```

**Comment by timocov** [comment]
I have met this bug (see branch `external_imports_impr` or commit https://github.com/timocov/dts-bundle-generator/commit/59ccc3464a8209c40f0b0b010526393e1fb6b1a2), but it is not fixed yet.

I need to some time to refresh what I did there and fix this bug (AFAIK fix for this bug should be accompanied by some "big" CLI changes, but I am not sure for now).

Thanks for reporting!

**Comment by e2tox** [comment]
Thank you for your great project. I already use it in https://github.com/agentframework/agentframework and I am plan to use in many other projects/library.

**Comment by timocov** [comment]
Moved from #11 

Additional example of the problem:

```ts
import { NamedDeclaration } from 'typescript'; // we can't use `* as ts` import here to bundle declarations
export interface Interface extends NamedDeclaration {}
```

For this code the tool will generate wrong definition as soon TypeScript has exports as `export = ts;` (and `ts` is namespace which merged into one from whole file):

```ts
export interface Interface extends NamedDeclaration {
}
```
