### ISSUE TITLE
Add option to not remove any comments

### ISSUE THREAD

**Issue by NanderTGA** [timocov/dts-bundle-generator#249]
First of all thank you for making this package, it is really useful to have.

I have noticed ever since I've started using this package that some comments seem to get stripped away while others don't.
The main reason I'm using this package is to easily share API typings with others, and it's a bit annoying when I have to copy paste the TS/JSDocs into the resulting file manually.

Could you please add some option to not strip away any comments? Thanks in advance.

**Comment by timocov** [comment]
Hi there, can you provide a reproduction for this issue?

**Comment by NanderTGA** [comment]
I don't have a reproduction yet, but I can tell you what it comes down to:

It seems to me (based on one of your tests) that it is intended behavior to strip away jsdocs from anything that is not in the entry file and keep all jsdocs that are contained in the entry file. (This exact thing happens when the entry file is a typescript file)

When the entry file is a javascript file though, the complete opposite happens:
The jsdocs in the entry file are stripped away, and the jsdocs contained in another file aren't. (I don't think this is intended behavior)

My problem is I don't want any jsdocs stripped away.

I'll try to get you a reproduction soon.

**Comment by timocov** [comment]
This is partially true - the tool strips comments only if a node is not intended to be exported. If a node is type-only (e.g. interface or type, but not a function or class) the tool will export it even if you don't export it explicitly. The rest of the comments stripping can be done in the compiler.

**Comment by NanderTGA** [comment]
You can find a reproduction [here](https://github.com/NanderTGA/dts-bundle-generator-bug).

**Comment by timocov** [comment]
@NanderTGA thanks for the repro! The issue goes down the compiler - it generates different dts output for js and ts files. From your example, if you run `tsc --declaration true` for both ts and js versions and compare the output you'll get something as follows:

`in.d.ts` for ts entry:

```ts
/**
 * This is the main export.
 */
declare const exportedThing: {
    /**
     * A thing.
     */
    importedThing: {
        someFunction(arg1: string, arg2: string): void;
    };
};
export default exportedThing;
```

`in.d.ts` for js entry:

```ts
export default exportedThing;
declare namespace exportedThing {
    export { importedThing };
}
import importedThing from "./importedThing.ts";
```

You can try it yourself [here](https://www.typescriptlang.org/dev/bug-workbench/?allowJs=true&emitDeclarationOnly=true&declarationDir=true&ts=5.0.3#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYC5Q1kBXaAKBAkXniwHcApAZwKNLIrHADMN5ociALbQCGHDAAeAOgBWTDhiEAHLMjSglq9dEgAVABbiA5qG7IsQ0ACJpwLWrS7DJ6x2AAqD2VAfQLpk1AtANoUCFEcVBoSW00aR8PYDJYXCYNGLjnIxxTAF5QAG8fUFLPb1LKvwBBQhzjBMrSpJLShx19erIAXw5Mx1AYbkRieAzYx2yTdy5efkERMRVJzpNpNAUKL0TCaHTE5NScdM1ljpdc0ALipvLW5tBa7mIcWExcOvRBrD3QJktoCE1vdfBBlChhKAUMYAIz+UJmDDIE7Q4giHDxEF+cDg1BWaEAJnhYSYcFwkChyGMaIEmKavmSTX+IgAYi83tgcAAKaEwgjpZAmAA0lOMBP5RBMAEoCAA3LAYCmFXq9Mj9dSDaDDUYadpOVa5MhAA): open the page, open debug tab at the left, scroll to `/index.d.ts` output. You can change `// @filename: index.js` to `// @filename: index.ts` check the output once again.

I assume this is the exactly difference you're referring to, right? If it is so, then it is the problem with the compiler as it omits some jsdocs from js code while it generates declaration files and it needs to be reported to the compiler repo [here](https://github.com/microsoft/TypeScript/issues).

**Comment by timocov** [comment]
Looks like this issue https://github.com/microsoft/TypeScript/issues/46010

**Comment by timocov** [comment]
Let me know if you have any questions and need more help.
