### ISSUE TITLE
/// <reference types="string" />emitted at top of file

### ISSUE THREAD

**Issue by danmarshall** [timocov/dts-bundle-generator#25]
I'm not sure why this is happening, hoping there is a way to suppress it.

**Comment by timocov** [comment]
You can specify what types should be "referenced" via `--external-types`. By default all libraries, which are detected as used in generated bundle, will be referenced in such way.

🤔 It is possible that we need to have some verbose output about the reason of usage external libraries (if we haven't it already).

For now you can provide a small example here and I will be able to provide you such info 🙂.

**Comment by danmarshall** [comment]
Thanks for the offer! Do you know why "string" is considered a library?

**Comment by timocov** [comment]
What version do you use?

The generated bundle does not use typings from `string.js`, right?

Unfortunately without small repro I cannot tell you why it is used in such way.

Some libraries (for example jqueryui) extend definitions from other libraries and may be referenced along with extendable library, but this case seems to be different.

**Comment by danmarshall** [comment]
Oh, yes I do use `string.js` - thank you for clearing up this confusion. I thought it was the internal `string` type. 👍
