### ISSUE TITLE
A lot of errors started to appear when trying to migrate to version 8

### ISSUE THREAD

**Issue by HarelM** [timocov/dts-bundle-generator#250]
**Bug report**

**Input code**

We have a huge library - maplibre-gl-js that uses this tool.

**Expected output**

No errors - it used to pass for version 7.2

**Actual output**

A lot of errors:
See here:
https://github.com/maplibre/maplibre-gl-js/actions/runs/4695006196/jobs/8323730861?pr=2338
in the build-dist:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/3269297/232137593-73eaba73-5c79-4d29-9a57-a513bbaf2246.png">

**Additional context**
I was trying my best to make sure I follow the rules defined in this tool to make sure we are able to generate d.ts files from the ts code of maplibre, we are using CI tools to make sure everything is checked and a dependabot CI failed after the release of version 8.
See here:
https://github.com/maplibre/maplibre-gl-js/pull/2338

Thanks for all the hard work invested in this tool!

Thanks!

**Comment by timocov** [comment]
Ah that's a nice one! It is related to the following breaking change

> Changed default behavior for module ModuleName statements (without quotes) (see https://github.com/timocov/dts-bundle-generator/issues/237 and https://github.com/timocov/dts-bundle-generator/pull/242)

but definitely it is a bug. I'll fix it shortly.

**Comment by timocov** [comment]
The fix has been published in [v8.0.1](https://github.com/timocov/dts-bundle-generator/releases/tag/v8.0.1).

**Comment by HarelM** [comment]
Thanks!!
