### ISSUE TITLE
feature request: Allow to keep imports

### ISSUE THREAD

**Issue by mix0000** [timocov/dts-bundle-generator#256]
I want to keep some of the imports. Looks like this is impossible according the docs. All imported libraries become included to outpup if they are exist in node_modules. 

```js
const dts = generateDtsBundle(
  [
    {
      filePath: "./src/sdk-component.ts",
      libraries: {
        // we need something like this:
        keepImports: ["libraryName"]
      }
    }
  ]
);
```

**input.ts**

```ts
import {SomeType} from "libraryName"
import {OtherType} from "includedLibrary"

interface A extends SomeType {};
interface B extends OtherType {};
```

**Expected output**

```ts
import {SomeType} from "libraryName"

declare OtherType {}

interface A extends SomeType {};
interface B extends OtherType {};
```

**Actual output**

```ts
declare SomeType {}
declare OtherType {}

interface A extends SomeType {};
interface B extends OtherType {};
```

Why I need this: 

I'm using dts-bundle-generator to create envirement for monaco-editor. 
I have library A where Im generating d.ts file and injecting it to monaco.
Then I have main project where im also using library A and generating d.ts file and I DONT need to generate library A declarations twice. 
So in main project I want to keep the imports because they are already generated and injected to envirement.

**Comment by timocov** [comment]
Hi tehre, can you provide actual repro? I don't quite understand what's going on here. From the config you didn't specify "inlined libraries" but from the "actual output" you have imports inlined. I assume that you just tried to create an example rather than actual repro (at least declaration looks wrong), but it confuses.

**Comment by mix0000** [comment]
@timocov I cant reproduce the problem in local repository. There is something wrong with my main project.
