### ISSUE TITLE
Yargs does not parse the command correctly

### ISSUE THREAD

**Issue by moltar** [timocov/dts-bundle-generator#258]
**Bug report**

**Input code**

Running the command like this:

```sh
dts-bundle-generator --project=tsconfig.json \
--out-file=src/bundled-types/tsup/tsup.ts \
--external-inlines=esbuild --external-inlines=rollup \
--external-inlines=source-map \
--external-inlines=tsup tsup-options/in.ts
```

**Expected output**

Command to work.

**Actual output**

Fails with:

```
Error: No input files specified
```

**Additional context**

When I added `console.log` to dumb yargs, here's how it interpreted:

```js
{
  _: [],
  project: 'tsconfig.json',
  'out-file': 'src/bundled-types/tsup/tsup.ts',
  o: 'src/bundled-types/tsup/tsup.ts',
  'external-inlines': [ 'esbuild', 'rollup', 'source-map', 'tsup', 'tsup-options/in.ts' ],
  verbose: false,
  silent: false,
  'no-check': false,
  'fail-on-class': false,
  sort: false,
  'inline-declare-global': false,
  'inline-declare-externals': false,
  'disable-symlinks-following': false,
  'respect-preserve-const-enum': false,
  'export-referenced-types': true,
  'no-banner': false,
  '$0': '../../node_modules/.pnpm/dts-bundle-generator@8.0.1/node_modules/dts-bundle-generator/dist/bin/dts-bundle-generator.js'
}
```

Notice that it added the input file `tsup-options/in.ts` to `external-inlines` option for some reason.

Separating the command with extra `--` works correctly:

```sh
dts-bundle-generator --project=tsconfig.json \
--out-file=src/bundled-types/tsup/tsup.ts \
--external-inlines=esbuild --external-inlines=rollup \
--external-inlines=source-map \
--external-inlines=tsup -- tsup-options/in.ts
                        ^^
```

**Comment by timocov** [comment]
Why do you think it doesn't parse it correctly? `--external-inlines` option is expected to be an array, so you could do something like `--external-inlines foo bar baz` without specifying `external-inlines` multiple times. Adding `--` as a separator is widely used pattern in CLI.

**Comment by slhck** [comment]
I just ran into this, and it's highly unintuitive since the error is not very helpful:

```
➜ npx dts-bundle-generator --out-file types.d.ts src/types/foo.ts        
Compiling input files...
Processing src/types/foo.ts
Writing src/types/foo.ts -> types.d.ts
Checking generated files...
Done in 9.99s

➜ npx dts-bundle-generator --out-file types.d.ts --external-inlines '@foo/bar' src/types/foo.ts

Error: No input files specified
```

When I add `--` before the positional arg, it works fine.

I understand that the underlying reason is that the `--external-inlines` option (being an array) consumes the input file as its second array entry.

Maybe having an example in the README would help?
It's very likely that people will have more than one external dependency to inline.

**Comment by timocov** [comment]
> Maybe having an example in the README would help?

@slhck sure, feel free to create a PR

**Comment by slhck** [comment]
It seems that the README even specifies a command that does not work?

```
./node_modules/.bin/dts-bundle-generator --external-inlines=@mycompany/internal-project --external-imports=@angular/core rxjs path/to/your/entry-file.ts
```

This will throw the aforementioned error because there is no `--` between the `external-imports` arguments and the final positional argument.
