### ISSUE TITLE
(love) Just to tell you how great your software is

### ISSUE THREAD

**Issue by aleluff** [timocov/dts-bundle-generator#260]
The real issue is maybe that opensource developers don't receive enough gratification.
Thanks to you, creator can build better software

Have a nice day =)

**Comment by timocov** [comment]
Hi @aleluff,

Thank you for your feedback! I don't know how did you know this, but yesterday wasn't the best day in my life to be frankly (nothing critical tho) and your message arrived just exactly when it was needed, absolutely perfect timing. I appreciate your kind words ❤️

**Comment by aleluff** [comment]
Thanks @timocov, always a pleasure to brighten people's day =) Specially the dark ones

Tell me if I can do something for you
