### ISSUE TITLE
[Feature Request] Inline all types as an option

### ISSUE THREAD

**Issue by Suyashtnt** [timocov/dts-bundle-generator#262]
I'm currently trying to get this tool to inline all types in my project. This is tedious and also inefficient. It would be nice to be able to tell dts-bundle-generator to inline ALL types from external code

**Comment by timocov** [comment]
Can you elaborate a bit more on your use-case please?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
