### ISSUE TITLE
Is there a quantity limit for exporting?

### ISSUE THREAD

**Issue by wszgrcy** [timocov/dts-bundle-generator#263]
I export trpc router declaration by this. When I add router declaration Exceeding a certain quantity,some type change to `any`,but If I use` type xxx=Routerxxx`,It can export part(The deeper reference is still `any`)
I change reference order and loss type method will change(to any).

**Comment by timocov** [comment]
There are no internal limitations for the amount of types being exported in the tool. But the compiler might have some? Do you have a repro for your issue?

**Comment by wszgrcy** [comment]
> There are no internal limitations for the amount of types being exported in the tool. But the compiler might have some? Do you have a repro for your issue?

if `Compiler`limit ,I must solve by my self.thanks!
The code is quite complex.I currently don't have time to verify
