### ISSUE TITLE
don't work with pnpm and turborepo

### ISSUE THREAD

**Issue by yovanoc** [timocov/dts-bundle-generator#269]
I don't know if its a bug or if I don't understand something but I can't find a way to make my use case working.
It appears that inside my turborepo monorepo, and using pnpm, dts-bundle-generator can't bring types from other packages.
I got a lot of `error TS2304: Cannot find name XXX` with XXX being types from other packages. I tried --external-inlines with these packages and changing --disable-symlinks-following but none of these works. What should I try?
thanks

edit: it appears that if I do relative imports like `../../../../../../packages` it works with dts-bundle-generator. but can't build my project.

**Comment by timocov** [comment]
Can you share the repro?

**Comment by yovanoc** [comment]
It's a private startup project so I can't but maybe I can try to make a minimal repro starting from turborepo examples

**Comment by timocov** [comment]
Yes please, it would be helpful. Otherwise it's hard to tell what's exactly wrong.

**Comment by yovanoc** [comment]
Ok here we go,: https://github.com/yovanoc/dts-repro

pnpm generate:api in the main-service app.

the generated api.d.ts don't include StaticType from packages/external-types

**Comment by timocov** [comment]
Hey @yovanoc, thanks for the repro. How does it work for you? I just opened your repro and vscode also highlights the same issue as the tool generates:

![image](https://github.com/timocov/dts-bundle-generator/assets/3112183/05d29e48-fe59-4c1e-ba66-e7b5c5ce3667)


```
$ pnpm generate:api

> @dts-repro/main-service@0.0.0 generate:api D:\projects\dts-repro\apps\main-service
> pnpm dlx dts-bundle-generator -o api.d.ts ./src/api.ts

Packages: +18
++++++++++++++++++
Progress: resolved 18, reused 18, downloaded 0, added 18, done
Compiling input files...
src/api.ts(2,33): error TS2307: Cannot find module '@dts-repro/external-types/dist/static-types' or its corresponding type declarations.

Error: Compiled with errors
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by timocov** [comment]
It seems that you're using composite projects that aren't supported right now (#93). As a workaround you can create a separate tsconfig for the tool that will include all needed files (basically just don't restrict any folders), something like this:

```
{
  "compilerOptions": {
    "module": "NodeNext",
    "paths": {
      "@dts-repro/*": ["../../packages/*"]
    },
    "types": ["node"],
    "moduleResolution": "NodeNext"
  },
  "exclude": ["node_modules"]
}
```

works fine:

```
$ pnpm generate:api

> @dts-repro/main-service@0.0.0 generate:api D:\projects\dts-repro\apps\main-service
> pnpm dlx dts-bundle-generator -o api.d.ts ./src/api.ts --project tsconfig.dts.json && cat api.d.ts

Packages: +18
++++++++++++++++++
Progress: resolved 18, reused 18, downloaded 0, added 18, done
Compiling input files...
Processing ./src/api.ts
Writing ./src/api.ts -> api.d.ts
Checking generated files...
Done in 3.04s
// Generated by dts-bundle-generator v8.1.2

export type InternalType = {
        someStr: string;
};
export type StaticType = {
        test: number;
};
export type Api = {
        internal: InternalType;
        static: StaticType;
};

export {};
```

**Comment by timocov** [comment]
Feel free to post any updates if it is not the only issue you're experiencing.

**Comment by yovanoc** [comment]
oh thanks for the info but when I do that on the real project I get `Error: Unknown top-level node kind (with modifiers): SourceFile.
If you're seeing this error, please report a bug on https://github.com/timocov/dts-bundle-generator/issues`

**Comment by timocov** [comment]
Make sure skibLibCheck is disabled. Can you provide a repro?

**Comment by yovanoc** [comment]
Can we talk in PM somewhere that I give you access to the repo?
Thanks for your time

**Comment by timocov** [comment]
Sure. Pls email me at timocov@gmail.com
