### ISSUE TITLE
Wildcard re-exports seem to be ignored

### ISSUE THREAD

**Issue by tomtheisen** [timocov/dts-bundle-generator#283]
**Bug report**

I'm not sure if this is a bug or feature request.  When using [wildcard re-exports](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#export-star-as-namespace-syntax), no corresponding entry is created in the output .d.ts bundle.

**Input code**

```ts
export * as cleanup from "./cleanup.js";
```

**Expected output**

```ts
export declare const cleanup: {
	foo: () => void; // or whatever was exported from cleanup.ts
	bar: () => void;
};
```

**Actual output**

```ts
// *nothing*
```

**Additional context**
Maybe there's some technical reason why this is impossible, but it seems like a useful feature.  Thanks for your time.

**Comment by timocov** [comment]
Can you share the content of cleanup.js as well?

**Comment by timocov** [comment]
What version of the tool you're using? It would be good to have a full reproduction actually. We have several tests for this feature and it looks like something is missing.

**Comment by tomtheisen** [comment]
I'm using 9.2.1.  Right now it's in a real code base.  I know a minimal reproduction would be more useful, so I'll work on extracting one.  Either I'll figure out what's causing it during the this, or I'll produce a minimal repro.  Either way, I'll update this thread with my finding.

**Comment by tomtheisen** [comment]
Alright I have some findings.  The short version is there is no bug.

I was using a different version of dts-bundle-generator  than I thought I was.  I'm using npm workspaces in a monorepo.  There were different versions installed in different folders.  Basically, the version that was actually exhibiting the problem was 8.0.1.  After updating the package in the correct location, everything seems to work.

Apologies for the incorrect bug report, and thanks for the tool
