### ISSUE TITLE
Prettify/format generated output

### ISSUE THREAD

**Issue by timocov** [timocov/dts-bundle-generator#29]
After #28 the generated output can have some a little bit "unformatted" code ([here](https://github.com/timocov/dts-bundle-generator/blob/b7f4bac7e6f3defb653fce028a9e2c20e5c4bb36/tests/test-cases/extend-other-module/output.d.ts#L6-L8) for example). We need to format it to make more readable.

**Comment by tianyingchun** [comment]
does ` with` `@typescript-eslint` configuration provider some API to do this? or `prettier` libraray

**Comment by timocov** [comment]
@tianyingchun maybe, but I don't think it's good idea to include them as deps to do "pretty formatting" itself. I guess TypeScript itself might have such option (e.g. in tsserver).

**Comment by cspotcode** [comment]
prettier's probably the easiest option by far.  TypeScript does have an AST printer.  Maybe just parse and print the output?

TypeScript also has a formatter, but I think it's very much built for the language service, and it has bugs.  It sends a list of modifications to the code editor, and you have to apply them to the code (lots of string splicing)
