### ISSUE TITLE
TS2307: Cannot find module *.module.css

### ISSUE THREAD

**Issue by theStrangeAdventurer** [timocov/dts-bundle-generator#300]
**Bug report**
Hi! When i'm trying to build my d.ts file 
`dts-bundle-generator -o ./dist/types/index.d.ts index.ts`
 I'm facing the following error:
```ts
error TS2307: Cannot find module './styles.module.css' or its corresponding type declarations.
```
It's worth noting that the TypeScript compiler have no issues with build and `tsc` works completely fine. Also i have declaration.d.ts which contain following:

```ts
declare module '*.module.css' {
    const classes: Readonly<Record<string, string>>
    export default classes
}
```

**Expected output**
// Nothing, it just works

**Actual output**
```ts
// src/index.tsx(2,20): error TS2307: Cannot find module './styles.module.css' or its corresponding type declarations.
```

Any insights or help on resolving this would be greatly appreciated. Thanks!

**Comment by timocov** [comment]
See https://github.com/timocov/dts-bundle-generator/discussions/232
