### ISSUE TITLE
export type * shouldn't export consts from the file

### ISSUE THREAD

**Issue by UziTech** [timocov/dts-bundle-generator#330]
**Bug report**

We are using dts-bundle-generator in marked and found that it is exporting some variables that aren't actually exported.

see https://github.com/markedjs/marked/issues/3426

**Input code**

https://github.com/markedjs/marked/blob/master/package.json#L90

**Expected output**

`block` and `inline` are not exported from `'marked'`

**Actual output**

https://cdn.jsdelivr.net/npm/marked@14.0.0/lib/marked.d.ts

**Additional context**

It looks like it thinks because the variables are exported from an internal file that they should be exported by marked but they are not exported by marked.

**Comment by UziTech** [comment]
I tried adding `--export-referenced-types=false` and that didn't seem to do anything.

**Comment by UziTech** [comment]
looks like this is because we export the types from the file the consts are exported from

```js
export type * from './rules.ts';
```

which only exports the types but dts-bundle-generator lists the consts as exported as well.

**Comment by timocov** [comment]
> which only exports the types but dts-bundle-generator lists the consts as exported as well.

This is where I believe the misunderstanding is. `export type` was never meant to "export types only", it "exports everything but as types" https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export: 

> export type only provides an export that can be used for type contexts, and is also erased from TypeScript’s output.

e.g. see [here](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEGcAsHsHcCiBbAlgFwFAgjBKN0BTAEwDFUAbIgLlFQDsSiAPAOhLfUmzHGYDGlAIYAnYelSwGddKICuRTLwgAzKkQbDktek1ZceqZAAdYo9KADeoVbFigAvrdGxkoAERtgsdNCKiALTq1B4A3MroAJ4mRKAAgqAAvKDRsbCqtvYRvHwhmtq6vv5B+YaYrGYWqTFxAFQubqAA5N4C0pDozTm5ahpaOnTtDJ3lleaWw51ZDikAjABMAMxhQA) that an exported via `export type` statement const `foo` can be imported from another module without any issues, which means that it should be preserved in output.

**Comment by timocov** [comment]
But related to using `export type` and keeping it as "type", here is the issue https://github.com/timocov/dts-bundle-generator/issues/290 (basically at the moment the compiler doesn't allow to differentiate these cases thus it is not done).
