### ISSUE TITLE
es2022: lacking support for arbitrary module namespace identifier names

### ISSUE THREAD

**Issue by laino** [timocov/dts-bundle-generator#334]
**Bug report**

**Input code**

```ts
export { variable as 'some-identifier' };
```

**Expected output**

```ts
export { variable as 'some-identifier' };
```

**Actual output**

```ts
// syntax error
export { variable as some-identifier };
```

**Additional context**

Valid syntax in ES2022 and supported by TypeScript. You have to set ``"module": "es2022"`` to use it.

**Comment by timocov** [comment]
Duplicate of #326
