### ISSUE TITLE
Types from `@types` is not imported when Error object is introduced

### ISSUE THREAD

**Issue by e2tox** [timocov/dts-bundle-generator#35]
Hi timocov,

It's me again. I found a minor issue that EventEmitter is not imported when `Error` object is introduced. `index.d.ts` will be generate only when you removed the Error object from the parameters. 

Following is the project to reproduce this issue. Fail with dts-bundle-generator@1.2.0

```
git clone https://github.com/e2tox/reproduce-dts-bundle-generator-node-imports.git
cd reproduce-dts-bundle-generator-node-imports
npm install
npm test
```

Thanks again

**Comment by timocov** [comment]
Hi!

I confirm this bug. As a workaround, you can restrict `external-types` to the empty array (actually you need to be sure that `node` is not referenced in this way), but I'll try to fix the issue shortly.

**Comment by timocov** [comment]
The version 1.2.1 with the fix is just published.

**Comment by e2tox** [comment]
Thank you timocov. That's totally awesome!!!
