### ISSUE TITLE
Statement `export * from 'other-module'` is not emitted

### ISSUE THREAD

**Issue by e2tox** [timocov/dts-bundle-generator#36]
Hi timocov,

I want share with you the new findings from my testing of yesterday.

In typescript, we can export the types from other module directly as following. But the following two lines are not emitted.

*Input File*
```typescript
/// <reference types="node" />
export { Server } from 'http';
export * from 'http2';
```

*Actual Result*
    ~~export { Server } from 'http';~~
    ~~export * from 'http2';~~

*Expected Result*
```typescript
/// <reference types="node" />
export { Server } from 'http';
export * from 'http2';
```

Please use this repo to reproduce this finding

```bash
git clone https://github.com/e2tox/reproduce-dts-bundle-generator-node-imports.git
cd reproduce-dts-bundle-generator-node-imports
npm install
npm test
cat index.d.ts
```

Thanks

**Comment by timocov** [comment]
Hi,

why do you need such re-export? Why do you re-export statements from other library/package? I guess you can just import it and then use it whenever you want and in result output you'll have import of this class/interface/etc.

**Comment by timocov** [comment]
I want to understand what case you have because it looks strange - why somebody should import `Server` or something else from `http2` package from your package but not from `http2` or `http` package?

**Comment by e2tox** [comment]
Hi timocov

Sorry make you confuse. There are few scenarios. 

1. programmable exports

```typescript
if (typeof URL !== 'undefined') {
   export { URL } from 'url';
}
else {
   export { URL } from 'whatwg-url';
}
```

2. Type validations

```typescript
import { YourClass } from 'your-class-interface';
import { CreateYourClass } from 'your-class-impl';

CreateYourClass() instanceof YourClass // maybe false. it depends on how npm install the library.
``` 

If NPM install two copies of `your-class-interface` in node_modules. The instanceof operator will return false. To prevent this. we need modify 'your-class-impl' to re-export YourClass and modify the code as below.

```typescript
import { CreateYourClass, YourClass } from 'your-class-impl';

CreateYourClass() instanceof YourClass // always true
``` 

3. Make something possible. Imaging the same code can deploy to Express, HAPI, Lambda, Azure Function....., So we need to create an abstraction layer over the frameworks

```typescript
import { Server } from 'your-awesome-server-framework'
// create your server
```

Run your code on Express
```base
npm install express-adaptor
npm install your-awesome-server-framework 
```

Run your code on Lambda
```base
npm install lambda-adaptor
npm install your-awesome-server-framework 
```

Run your code on Azure Function
```base
npm install azure-function-adaptor
npm install your-awesome-server-framework 
```

**Comment by timocov** [comment]
Ok, your description sounds reasonable, thanks!

I'll fix it soon.
