### ISSUE TITLE
Add 'declare' to classes

### ISSUE THREAD

**Issue by danmarshall** [timocov/dts-bundle-generator#43]
Hi Evgeniy,

Some of the .d.ts files I am using have classes declared without the use of the `declare` keyword:
```js
class Bounds {
	x1: number;
	y1: number;
	x2: number;
	y2: number;
}
```
TypeScript does not seem to have any issue with these when they are in module files. However, after generating with dts-bundle-generator, TypeScript is not as forgiving??

![image](https://user-images.githubusercontent.com/11507384/41693696-520e37bc-74bb-11e8-8c8d-780451b29554.png)

So, perhaps you might always emit the `declare` keyword if it is not already present on `class`es.

**Comment by danmarshall** [comment]
Ok, here is a repo which shows my issue:
https://github.com/danmarshall/dts-bundle-gen

**Comment by timocov** [comment]
Version [1.5.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v1.5.0) is released.

**Comment by danmarshall** [comment]
Thanks!!!
