### ISSUE TITLE
Something went wrong - value cannot be null

### ISSUE THREAD

**Issue by danmarshall** [timocov/dts-bundle-generator#44]
Hello, I hit [this error](https://github.com/timocov/dts-bundle-generator/blob/752a742c2fe8a47484fb6ad282bc7116e211829b/src/bundle-generator.ts#L379).

I was able to work around it by adding `return false` above the `throw`.

### Repro
My repo is https://github.com/danmarshall/vega-typings
clone
switch to the `umd2` branch
`npm install`
`npm run bundle`

**Comment by timocov** [comment]
Hi,

wow, nice catch, thank you! 🙂 

> I was able to work around it by adding return false above the throw.

Unfortunately, seems this is not a good solution for this problem - if you add the code above in the `index.d.ts`, then in generated declaration you will not have `import` of `None`:

```ts
import { None } from 'vega-util';
export declare const A: typeof None;
```

I'll prepare the fix for the problem soon.

**Comment by timocov** [comment]
Version [1.5.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v1.5.0) is released.
