### ISSUE TITLE
Re-exporting support

### ISSUE THREAD

**Issue by joseluisq** [timocov/dts-bundle-generator#51]
Hi! happy with your package. It works well at the moment.
However It would be great some __re-exporting support__, consider the following example:

__Input:__ `local.ts`

```ts
import { Vue } from 'vue';

export function spyComponent (component: Vue): void { }

export { Vue }
```

__Result:__ `local.d.ts`

```ts
import { Vue } from 'vue';

export declare function spyComponent (component: Vue): void;
```

*__Note:__ `declare` in "export function" is not necessary.*

**Comment by timocov** [comment]
Hi,

try to use `export { Vue } from 'vue';`. I hope it should help in your case (see #36).

**Comment by joseluisq** [comment]
> Hi,
> 
> try to use export { Vue } from 'vue';. I hope it should help in your case (see #36).

I got an `Duplicate identifier...` error when I try to export it directly from importing. That occurs because I need to use `Vue` too.

**Comment by timocov** [comment]
@joseluisq can you please provide your steps to reproduce (with installing packages, running commands, configs)? It seems that I have some problem with producing the error - the similar code is compiled without any errors:

```ts
import { AccessorDeclaration } from 'typescript';
export function doStuff(arg: AccessorDeclaration): void {}
export { AccessorDeclaration } from 'typescript';
```

**Comment by joseluisq** [comment]
Sorry, I fixed. Now works.

```ts
import { Vue } from 'vue'
export function spyComponent (component: Vue): void { }
export { Vue } from 'vue'
```

But `export { Vue } from 'vue'` is a temporal solution to `export { Vue }`.
