### ISSUE TITLE
Error: Debug Failure. False expression

### ISSUE THREAD

**Issue by mxswat** [timocov/dts-bundle-generator#52]
Hello, I'm getting this error `Error: Debug Failure. False expression: Paths must either both be absolute or both be relative`.

It happens only when I'm trying to add a class that extends another class from another directory.

Can you please explain to me why I'm getting this error?

**Comment by timocov** [comment]
Hi,

can you please provide a small repro for this error? Does it happened if you compile with `tsc`? What version of typescript do you have?

**Comment by timocov** [comment]
I going to close this issue due to inactivity. Please feel free to reopen it if needed.
