### ISSUE TITLE
Multiple input files?

### ISSUE THREAD

**Issue by mweiczorek** [timocov/dts-bundle-generator#65]
How do I specify multiple .ts/.d.ts files as input? Or to specify a directory of d.ts files to merge? My application doesn't have a starting point per se, so some files are being omitted. Please advise.

**Comment by mweiczorek** [comment]
Hi. The application consists of many singleton files, but they're all imported and combined in a standard index.js file (that requires .js from the  projects ./lib directory where compiled .js files reside), but I solved the issue by writing a .ts file that does the same thing, but imports .ts files from the project's ./src directory.

I haven't found a way to automate this, since they require/import from different places.

**Comment by mweiczorek** [comment]
I also run the command:
`dts-bundle-generator index.ts -o index.d.ts`
But I get error:  `error TS6053: File 'index.d.ts' not found.`

I create an empty 'index.d.ts' file, run the command again, and I get this error:
`error TS6053: File 'index.d.ts' not found.`

**Comment by mweiczorek** [comment]
Hi, my tsconfig.json file is here: 
https://github.com/mweiczorek/chromecast-js/blob/master/tsconfig.json

It may be that I'm not doing things right, I've never submitted a consumable package before. I have a few projects that need this library, so it's easier to publish to NPM than copy files from one project to another.

**Comment by timocov** [comment]
I just cloned this repo, install deps and run `npm run dts` and it compiles successfully. Could you provide steps to reproduce?

**Comment by timocov** [comment]
Hey @mweiczorek, do you have any updates on this?
