### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by wKovacs64** [timocov/dts-bundle-generator#66]
**Bug report**

I am importing a specific file from a library on npm, e.g. `import file1 from 'someLib/src/file1'`. To get its types to work (from `@types/someLib`), I have to basically reassign its types to that specific file by including a separate `someLib.d.ts` declaration file in my project that looks like this:
```ts
declare module 'someLib/src/file1' {
  import someLib from 'someLib';

  export default someLib;
}
```
Both `tsc` and my IDE integration are okay with this and pick up the types, but `dts-bundle-generator` fails to see it somehow and throws the following error:
```
src/consumer.ts(1,19): error TS7016: Could not find a declaration file for module 'someLib/src/file1'. 'node_modules/someLib/src/file1.js' implicitly has an 'any' type.
```
I can get it to pass if I set `"strict": false` in `tsconfig.json`, but I don't want to do that. As a workaround, I can prefix the import with a comment to disable type-checking (`// @ts-ignore` before `import someLib from 'someLib/src/file1`) or create a separate `tsconfig.json` just for `dts-bundle-generator` with `strict` disabled, but I thought I should bring it up here to see if it's a bug or if there's some configuration I've got wrong.

This might be related to #50 but when I tried a triple-slash referenced as proposed there, it included the contents of `someLib.d.ts` in the generated `.d.ts` which threw several errors when it attempted to validate the generated file (and I've been told the community is moving from triple-slash references to modules anyway?). I don't understand enough about the `declare module` and `import` interop/compatibility yet to fully grasp what's possible and what isn't, but I don't think I can import my `someLib.d.ts` manually. Also, the usage of `someLib` is internal only so the types do not need to appear in the output of `dts-bundle-generator`.

**Additional context**

CLI command and options:
```
dts-bundle-generator --umd-module-name myLib --out-file types/myLib.d.ts src/myLib.ts
```

P.S. Thanks for your work, this project is great. ❤️

**Comment by timocov** [comment]
I guess that at the moment you have the similar problem, if we apply the following patch to 4e516cd:

```diff
diff --git a/tests/test-cases/custom-types-folder/input.ts b/tests/test-cases/custom-types-folder/input.ts
index 5792d3b..6c52509 100644
--- a/tests/test-cases/custom-types-folder/input.ts
+++ b/tests/test-cases/custom-types-folder/input.ts
@@ -1,3 +1,5 @@
+/// <reference path="./types/fake-types-lib-2/index.d.ts" />
+
 import { Data } from 'fake-types-lib-2/data';
 
 export type MyData = Data | string;
diff --git a/tests/test-cases/custom-types-folder/tsconfig.json b/tests/test-cases/custom-types-folder/tsconfig.json
deleted file mode 100644
index 0969771..0000000
--- a/tests/test-cases/custom-types-folder/tsconfig.json
+++ /dev/null
@@ -1,9 +0,0 @@
-{
-	"extends": "../../tsconfig.json",
-	"compilerOptions": {
-		"typeRoots": [
-			"node_modules/@types",
-			"./types"
-		]
-	}
-}
```

There are the following changes:

1. Removed specific for the test case `tsconfig.json` file with overridden `typeRoots` compiler option.
1. Added triple-slash directive in the input file of the test.

Yeah, in this case we'll have additional output in the generated file:
```ts
export declare module "fake-types-lib-2/data" {
    export { Data } from 'fake-types-lib-2';
}
```

**Comment by wKovacs64** [comment]
I tried the first suggestion (custom `typeRoots`) but it didn't appear to do anything different. I still got the following:
```
src/consumer.ts(1,19): error TS7016: Could not find a declaration file for module 'someLib/src/file1'. 'node_modules/someLib/src/file1.js' implicitly has an 'any' type.
```
When I try the triple-slash directive, it generates the types but I get this on validation:
```
types/myLib.d.ts(211,1): error TS2668: 'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.
types/myLib.d.ts(211,23): error TS2665: Invalid module name in augmentation. Module 'someLib/src/file1' resolves to an untyped module at 'node_modules/someLib/src/file1.js', which cannot be augmented.
types/myLib.d.ts(212,21): error TS2307: Cannot find module 'someLib'.
Error: Compiled with errors
```

**Comment by timocov** [comment]
So, summarizing the above this is what you need to do to fix this problem:

1. Create folder in your project with custom types (for example, `./src/types` or `./types` or any other as you wish - a name and a path of the folder does not matter).
1. Add this folder to your `tsconfig.json` as `typeRoots` - see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types (do not forget add `./node_modules/@types` as well in this list if you want to use types from `@types`).
1. Place your custom types in that folder (you can use 4e516cd as example).

**Comment by timocov** [comment]
Can I take a look at project you're working on to play with this?

**Comment by wKovacs64** [comment]
Sure, it's https://github.com/wKovacs64/hibp

The custom type is currently in `src/internal/jssha.d.ts` but I can move it if needed.

**Comment by timocov** [comment]
Great! What steps to reproduce the problem and what branch I need to checkout?

**Comment by wKovacs64** [comment]
Remove the `// @ts-ignore` at the top of `src/pwnedPassword.ts` and run `yarn build:types`. The current branch (develop) is fine.

**Comment by timocov** [comment]
Ok, let me check.

**Comment by wKovacs64** [comment]
Thanks. Sorry, I was trying to keep the problem generic enough that you wouldn't have to mess with my specific project, but sometimes concrete examples are best I guess. 🙂

**Comment by timocov** [comment]
Notes for someone who want to fix this:

- See my comment https://github.com/timocov/dts-bundle-generator/issues/66#issuecomment-451776172.
- We already have function, which detects whether file from `typeRoots` or not (see [this code](https://github.com/timocov/dts-bundle-generator/blob/4e516cd4a00bf7ea4abfa11af296efad48aeb91c/src/module-info.ts#L61-L65)). It is possible that it might help (or the approach).
- TypeScript's API does not have `parseConfigFileWithSystem` in public, so we need to or implement the same function (or very similar), or ask TypeScript's team to make it public.
- I guess that changes should be [somewhere here](https://github.com/timocov/dts-bundle-generator/blob/4e516cd4a00bf7ea4abfa11af296efad48aeb91c/src/compile-dts.ts#L22)
- Pay attention on [this](https://github.com/timocov/dts-bundle-generator/blob/4e516cd4a00bf7ea4abfa11af296efad48aeb91c/src/compile-dts.ts#L60-L65) - it might works wrong after these changes.

**Comment by wKovacs64** [comment]
Interesting, nice find! I see also including `jssha-src` in the `types` array in `tsconfig.json` works as an alternative to the triple-slash reference, which I think I prefer.
```json
"typeRoots": ["node_modules/@types", "./src/@types"],
"types": ["node", "jsdom", "jest", "jssha-src"]
```
Additionally, it seems I can nest the custom module declaration in a structure that mirrors the actual types and refer to it as such (replacing `jssha-src` with `jssha/src`):

![image](https://user-images.githubusercontent.com/1288694/50742104-f3e9ee00-11c3-11e9-86c6-9f773edd9617.png)
```json
"typeRoots": ["node_modules/@types", "./src/@types"],
"types": ["node", "jsdom", "jest", "jssha/src"]
```
👍 

Thanks @timocov, I think this is a fine workaround for now. I appreciate you digging into this.

**Comment by timocov** [comment]
> I see also including jssha-src in the types array in tsconfig.json works as an alternative to the triple-slash reference

Yeah, it looks great. I forgot about `types` and didn't check it.

Actually I thought (for a moment) that this is a bug in TypeScript, but your idea gives insight - the reason of this "strange" behavior (that TypeScript doesn't add all types from `typeRoots` to the compilation) is `types` compiler option. Thank you!

I don't think that there is a bug in `dts-bundle-generator` anymore 🙂. If your problem is fixed, can we close the issue for now?

**Comment by wKovacs64** [comment]
Great, no bug after all! Thanks again.
