### ISSUE TITLE
Generated declaration file contains import statements

### ISSUE THREAD

**Issue by badeball** [timocov/dts-bundle-generator#70]
**Bug report**

I'm trying to utilize this tool, but I experience an issue where the generated bundle contains an import statement (which I obviously am trying to avoid by creating a bundle). I've uploaded the example [here](https://gist.github.com/badeball/6663e9d2a7437bffadbd488ccfdb4cec).

Is this a bug or am I just doing something wrong?

The *actual output* can be generated with the following commands.

```
$ git clone https://gist.github.com/badeball/6663e9d2a7437bffadbd488ccfdb4cec
$ cd 6663e9d2a7437bffadbd488ccfdb4cec
$ npm install
$ dts-bundle-generator -o index.d.ts index.ts
$ cat index.d.ts
```

**Input code**

```ts
// foo.ts
export interface FooNode {
  type: "foo";
  number: number;
}

export default function foo (): FooNode {
  return {
    type: "foo",
    number: 5
  };
}

// index.ts
import foo from "./foo";

export default class SomeClass {
  foo() {
    return foo();
  }
}
```

**Expected output**

```ts
// index.d.ts
// index.d.ts
export interface FooNode {
	type: "foo";
	number: number;
}
export default class SomeClass {
	foo(): FooNode;
}
```

**Actual output**

```ts
// index.d.ts
export interface FooNode {
	type: "foo";
	number: number;
}
export default class SomeClass {
	foo(): import("./foo").FooNode;
}
```

**Additional context**

dts-bundle-generator: v2.0.0
node: v11.3.0

**Comment by timocov** [comment]
Hi,

it looks like the TypeScript generates `import("./foo").FooNode` for return type of `SomeClass::foo` method. I'm not sure that we can handle this correctly as soon `dts-bundle-generator` does not change declaration, it just filter it with unused nodes and adds/removes the `export` keyword (maybe something more, but still not so "big thing" as change return type). But I'll investigate this.

As workaround you can just specify return type of this method just adding `foo(): FooNode {}` to your function.

**Comment by badeball** [comment]
Thanks for the quick response! The workaround works splendidly. I'll leave it up to you to close / keep the issue open and understand if this is a "no fix" kind of thing.

**Comment by timocov** [comment]
As soon it can be easily fixed via adding type of return value and possible hard way to fix it I'm going to close it for now. Feel free to reopen if you'll have problems with that.
