### ISSUE TITLE
Imports globals from @types/react

### ISSUE THREAD

**Issue by ben-mckernan** [timocov/dts-bundle-generator#71]
**Bug report**
When using the external-imports flag with react, the tools doesn't seem to recognize that certain types are global and imports them from react in the declaration file. This causes an error during the generated file check.

```
$ dts-bundle-generator -o index.d.ts index.tsx --external-imports react
Compiling input files...
Processing index.tsx
Adding import with name "HTMLButtonElement" for library "react"
Adding import with name "FunctionComponent" for library "react"
Adding import with name "HTMLAttributes" for library "react"
Writing index.tsx -> index.d.ts
Checking generated files...
index.d.ts(1,45): error TS2305: Module '"./node_modules/@types/react"' has no exported member 'HTMLButtonElement'.
Error: Compiled with errors
```

**Input code**

```tsx
import React, { FunctionComponent, HTMLAttributes } from "react";

interface ButtonProps extends HTMLAttributes<HTMLButtonElement> { }

export const Button: FunctionComponent<ButtonProps> = (props) => <button {...props} />;
```

**Expected output**

```ts
import { FunctionComponent, HTMLAttributes } from "react";
export interface ButtonProps extends HTMLAttributes<HTMLButtonElement> {
}
export declare const Button: FunctionComponent<ButtonProps>;
```

**Actual output**

```ts
import { FunctionComponent, HTMLAttributes, HTMLButtonElement } from 'react';
export interface ButtonProps extends HTMLAttributes<HTMLButtonElement> {
}
export declare const Button: FunctionComponent<ButtonProps>;
```

**Comment by timocov** [comment]
Hi,

sorry for long answer - I was a little bit busy last week 🙁

Your code doesn't compile in clean env. Here what I did:

1. `mkdir temp`
1. Add `index.tsx` file with your content
1. `npm install typescript @types/react dts-bundle-generator`
1. `./node_modules/.bin/tsc --init`
1. Add `"lib": ["dom", "es5"]` to `tsconfig.json`
1. Add `"jsx": "react"` to `tsconfig.json`
1. Run `./node_modules/.bin/tsc`

and after that I get the following error:
```
error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

To fix it I use the following code in `index.tsx`:
```tsx
import * as React from "react";

interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement> { }

export const Button: React.FunctionComponent<ButtonProps> = (props) => <button {...props} />;
```

(I just replaced named import with import the whole `React`).

After that your code compiles successfully.

But `dts-bundle-generator` works fine too: I run it with `./node_modules/.bin/dts-bundle-generator index.tsx --external-types react`. Here is output:

```ts
/// <reference types="react" />

export interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement> {
}
export declare const Button: React.FunctionComponent<ButtonProps>;
```

Btw, see note for 2nd limitation [in the README](https://github.com/timocov/dts-bundle-generator#known-limitations) - it looks like this is exactly what you need 🙂

**Comment by timocov** [comment]
Hi @ben-mckernan,

sorry for long delay of answer - I was a little bit busy last week.

>  I still see a problem following the steps that you've outlined if I use this flag instead of `--external-types`.

Yes, you'll have an error for react types if you use `--external-imports` flag for it instead of `--external-types`. I need to debug why dts-bundle-generator treats `HTMLButtonElement` as interface declared in react's types. Just let me check and I'll be back with results in couple of days.

> But perhaps this scenario is covered by the 2nd known limitation you referred to?

I believe there is a simple workaround for this, which you can use to avoid such errors, but let me check what's going on here.

**Comment by timocov** [comment]
Hm, it looks like the reason of that import is [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/global.d.ts) with definitions of all DOM elements...

**Comment by timocov** [comment]
So, I confirm this bug, and I'll fix it soon.

_(this issue is a little bit related to #59)_

**Comment by timocov** [comment]
Version [v2.1.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v2.1.0) has been published! 🎉
