### ISSUE TITLE
Override `skipLibCheck` option when checking output file validity

### ISSUE THREAD

**Issue by Swatinem** [timocov/dts-bundle-generator#72]
https://github.com/timocov/dts-bundle-generator/blob/661226c5684a8c198c2841e8badc8fb1af3409fc/src/bin/dts-bundle-generator.ts#L215-L223

It should be trivial to just override that option and check the output file regardless of what was set.

**Comment by timocov** [comment]
Yeah, you're right! If somebody don't want to check generated output - it can use `--no-check` CLI flag for that.

**Comment by timocov** [comment]
Version [v2.1.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v2.1.0) has been published! 🎉
