### ISSUE TITLE
Error with tsconfig `extends` option set to a node module path

### ISSUE THREAD

**Issue by medfreeman** [timocov/dts-bundle-generator#82]
**Bug report**

Having the `extends` option set in tsconfig.json to a path referring to a node module results in an error.

**Input code**

*tsconfig.json*
```json
{
  "extends": "my-module/tsconfig",
  "include": ["./src/**/*"],
  "compilerOptions": {
    "baseUrl": "./src/",
    "outDir": "./dist/"
  }
}
```

```shell
$ dts-bundle-generator -o dist/index.d.ts src/index.ts
```

**Expected output**

```shell
Compiling input files...
Compiler option `outDir` is not supported and will be removed while generating dts
Processing src/index.ts
Writing src/index.ts -> dist/index.d.ts
Checking generated files...
Done in 3.70s
```

**Actual output**

```shell
Compiling input files...
message TS6096: File 'my-module/tsconfig' does not exist.
Error: Error while processing tsconfig compiler options
error Command failed with exit code 1.
```

**Additional context**

After investigation it seems that the `basePath` argument (3rd) to [`ts.parseJsonConfigFileContent`](https://github.com/timocov/dts-bundle-generator/blob/6630db8c1d05cf40eb76e0d0cd5cf0a750c48eae/src/get-compiler-options.ts#L23) has to be an absolute path for the `extends` module resolution to work properly.

I'll submit a pull request in a minute.

**Comment by timocov** [comment]
Version 3.0.0 has been published!
