### ISSUE TITLE
Cannot find namespace 'fs'

### ISSUE THREAD

**Issue by antoninbouchal** [timocov/dts-bundle-generator#84]
Hi.

When I use node core packages as `fs` there is issue with generating declaration file via bundle.

When I have in my code this:
```ts
import * as fs from 'fs';

export default class TestClass {
    public getStats(path: string): Promise<fs.Stats> {
        ...
    }
}
```

dts-bundle-generator create declaration similar to this:
```ts
/// <reference types="node" />

import { Stats } from 'fs';

declare class TestClass {
	getStats(path: string): Promise<fs.Stats>;
}
```

# I created repository with whole problem here:
https://github.com/Scorpio1337/dts-generator-issue

Maybe I doing something wrong.

For solution I used hack with require (it is in repo too), but it's really ugly.

**Comment by timocov** [comment]
Hi @Scorpio1337,

actually this is second known limitation (see https://github.com/timocov/dts-bundle-generator/blob/master/README.md#known-limitations). I believe this issue can be solved along with other issues marked with https://github.com/timocov/dts-bundle-generator/issues?q=is%3Aissue+is%3Aopen+label%3Adetect-import-path-problem label.

As workaround you can try to import without renaming, e.g. `import { Stats } from 'fs'`, but it can doesn't work in some cases.

**Comment by musicode** [comment]
@timocov 

I have a similar issue.

For example, there are some helper functions in `a.ts`, I hope to export `a` as a property from `b`.

but `dts-bundle-generator` can't do that.

a.ts

```js
export function doSomething1() {
}

export function doSomething2() {
}
```

b.ts

```js
import * as a from './a'

export default {
  a: a
}
```

**Comment by timocov** [comment]
@musicode what error you get? It looks your issue is about 2nd known limitation (see https://github.com/timocov/dts-bundle-generator#known-limitations).

**Comment by musicode** [comment]
yes, It's 2nd known limitation, but I think it's maybe useful.

for my scenario, I have a module `a` that define some helper functions.

then I want to export `a` from entry point.

b.ts

```js
import * as a from './a'

export default {
  a: a
}
```

then I can use it like below:

```js
import b from 'b'
b.a.doSomething1()
```

It's a common case, I need type suggestion in my vscode.but `dts-bundle-generator` will report `a is not define`.

so i have to write a declaration file manually, and set the type for `a`.

```js
import * as a from './a'
import aType from './aType'

export default {
  a: aType: a
}
```

It's ok, but it's so trouble and hard to maintenance.

**Comment by antoninbouchal** [comment]
Thank you guys ... As I sad, I use right now "hack" with require.
It is not good because I must use is really often. :D
