### ISSUE TITLE
Feature request: ignore symbols from js modules.

### ISSUE THREAD

**Issue by shrinktofit** [timocov/dts-bundle-generator#88]
![image](https://user-images.githubusercontent.com/28807867/56344475-1e4e3d00-61f0-11e9-9bd8-26a6232775aa.png)

My project mixes the use of ts and js. When a ts import/export a js module, the declaration file (directly generated by tsc) contain errors, so the dts-bundle-generator cannot read it and generate bundled one.

**Comment by timocov** [comment]
Hi,

can you please provide a repro of your problem? I don't think that understand you correctly (also I don't know Chinese and don't know what errors you have on the screenshot).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any updates, feel free to reopen it.
