### ISSUE TITLE
Feature request:  line terminator option

### ISSUE THREAD

**Issue by WaiSiuKei** [timocov/dts-bundle-generator#90]
Seems that the default line terminator is CRLF, it will be great if Mac users can specify a LF line terminator.

**Comment by timocov** [comment]
Hi,

I believe everywhere in this repo [I have used `\n` terminator for output](https://github.com/timocov/dts-bundle-generator/blob/814ea3b7616b1a32c347e15c143dd7f39afffde1/src/generate-output.ts#L23-L62).

I'm not sure, but it looks like this line ending is added by TypeScript compiler. Did you have a `newLine` compiler option set?

**Comment by WaiSiuKei** [comment]
Thanks for your reply, the `newLine` options does works.
