### ISSUE TITLE
Add 'declare' to variables

### ISSUE THREAD

**Issue by timocov** [timocov/dts-bundle-generator#92]
**Bug report**

The same as in #43, but for variables/constants (see https://github.com/timocov/dts-bundle-generator/pull/46#issuecomment-497429341).

/cc @aleclarson

**Comment by timocov** [comment]
It looks like it isn't issue - see https://github.com/timocov/dts-bundle-generator/pull/46#issuecomment-511150439.

**Comment by timocov** [comment]
Just to be sure that @aleclarson got this notification - ping :)

**Comment by aleclarson** [comment]
IIRC, I didn't actually run into an issue with this, but it looked suspicious I guess. If it works, then you're in the clear I think. 👍

**Comment by timocov** [comment]
Ah, great! 🙂 Then I'm closing that issue for now. If someone faced that issue - feel free to ping me here or create another issue with repro code.

Thank you!
