### ISSUE TITLE
Support for import path rewriting

### ISSUE THREAD

**Issue by aleclarson** [timocov/dts-bundle-generator#94]
I use `paths` in `tsconfig.json` and `tsc` doesn't transform `import` paths automatically.

Basically, just need a way to intercept `import` statements (using the programmatic API) so I can change where they are pointing.

Alternatively, this package could respect `paths` in `tsconfig.json` and do the mapping for me, which could be opt-in if that's a concern.

**Comment by timocov** [comment]
Do you have a repo with repro or any example? For now I'm not sure that understand you correctly 🙁

**Comment by aleclarson** [comment]
I use the `compilerOptions.paths` option in `tsconfig.json` to shorten some of my `import` paths. 
[Read this](https://decembersoft.com/posts/say-goodbye-to-relative-paths-in-typescript-imports/) for more details.

Currently, `tsc` emits any `import` paths as-is, even if `compilerOptions.paths` is being used. 
[Read this](https://github.com/microsoft/TypeScript/issues/10866) for more details.

So that means bundlers (like `webpack` and `dts-bundle-generator`) are responsible for resolving the `import` paths correctly, which means this package should either (1) respect `compilerOptions.paths` when defined, and/or (2) provide an option for manually resolving any paths.

LMK if I'm still confusing you. 😄

**Comment by timocov** [comment]
> LMK if I'm still confusing you.

Yeah, I've know about `paths` compiler options and for what it should be used/how it works. So, did you mean that `dts-bundle-generator` does not respect that option? If so, do you run it after `tsc` over `d.ts` files or just for `.ts` files? I just want to understand what doesn't work and what did you do to get incorrect behavior 🙂

**Comment by timocov** [comment]
If you have a repo where you're able to reproduce this error, it would be awesome.

**Comment by aleclarson** [comment]
Try this: https://github.com/aleclarson/repro/tree/dts-2

Notice how `dts-bundle-generator` generates this:
```ts
import { Bar } from '@foo/bar';

export declare type Foo = (bar: Bar) => void;
export declare const foo: Foo;
export { bar } from 'bar';

export {};
```

And `tsc` generates this:
```ts
import { Bar } from 'bar';
export declare type Foo = (bar: Bar) => void;
export declare const foo: Foo;
export { bar } from 'bar';
```

**Comment by timocov** [comment]
Which one import is correct: `@foo/bar` or just `bar`?

**Comment by timocov** [comment]
Also, did you try to disable symlinks following for `dts-bundle-generator`? See https://github.com/timocov/dts-bundle-generator/issues/91#issuecomment-497292389 and https://github.com/timocov/dts-bundle-generator/issues/53#issuecomment-499239039

**Comment by aleclarson** [comment]
> Which one import is correct: `@foo/bar` or just `bar`?

Based on what I've said in this thread, I would say `@foo/bar` is the correct one for `dts-bundle-generator` to output.

**Comment by timocov** [comment]
Sorry, I'm a little bit confused. Is `tsc`'s output incorrect for you? What's a case when you need to treat one node_module package as another node_module package, but only for tsc (without linking it via `package.json`/yarn/npm)? In this case I would say that `tsc`'s output is more accurate and `dts-bundle-generator` should generate the same one, not with `@foo/bar`.

Sorry for boring you, but I would like to better understanding your case to make better decision about fix.

**Comment by aleclarson** [comment]
> Sorry for boring you,

No worries. Thank you for your time! ❤️ 

> I would like to better understanding your case to make better decision about fix.

In the `react-spring` monorepo, I'm using `compilerOptions.paths` so I can import `shared/*` as a shortcut for `@react-spring/shared/src/*` during local development (see [here](https://github.com/react-spring/react-spring/blob/f365c71a55f17605a4595dc4f7820eb9b2d6e4c8/tsconfig.json#L11-L14)).

Like it says in https://github.com/microsoft/TypeScript/issues/10866, `tsc` leaves imports as-is even if `compilerOptions.paths` is used, which I have no problem with. But since `dts-bundle-generator` is a **bundler** first and foremost, I expect it to swap out `shared` with `@react-spring/shared` so that the bundle has `import` paths that can be resolved by looking in `node_modules`.

I can't just use...
```json
"dependencies": {
  "shared": "file:node_modules/@react-spring/shared"
}
```
...because `shared/globals` wouldn't point to `@react-spring/shared/src/globals` like it's supposed to.

And I can't just use...
```json
"dependencies": {
  "shared": "file:node_modules/@react-spring/shared/src"
}
```
...because npm expects a `package.json` to exist for dependencies.

So the easiest route is to rewrite the `import` paths to point to `@react-spring/shared` (which will have the proper file structure in its `dist` directory once it's published).

As you can see, this is a pretty complex situation. I've done a lot of thinking about this, and I'm pretty confident that rewriting the `import` paths is the best way to go.

**Comment by timocov** [comment]
> But since dts-bundle-generator is a bundler first and foremost, I expect it to swap out shared with @react-spring/shared so that the bundle has import paths that can be resolved by looking in node_modules.

> I'm pretty confident that rewriting the import paths is the best way to go.

I'm not sure that it's what `dts-bundle-generator` should do. Afaik webpack (for instance) doesn't change your imports while bundles the code. Bundler should bundle the code and build something like "library", but not change external linking.

For path-rewriting I would suggest you use custom transformations of the TypeScript compiler (something like https://github.com/LeDDGroup/typescript-transform-paths).

**Comment by timocov** [comment]
@igorpupkinable Sorry for late reply here.

> Remove paths from packages/fe-components/tsconfig.json

The reason why this step makes the tool is working is that there are 2 "levels" of linking packages:
- fs symlinks, which are generated by yarn monorepo I guess
- TS `paths`, compiler-only "links"

It looks like they are applying in opposite order, i.e. `paths` are first, then fs symlinks. By removing `paths` you let compiler to use fs symlinks and that's why it is working.

The original issue is the tool relies on fs path rather that import query (which obviously might be different across the project).

Relying on `paths` is kind of tricky, because if you're using `paths` it doesn't mean that this folder (or a file) should be treated as an "external". You could add one of your folders to the `paths` just to decrease level of exiting while writing a path in import statement ('../../../../../../../file' vs '~root/file').

Moreover, I'm not sure, but most likely ts compiler will resolve module's name before accessing FS api (you said that enabling `disable-symlinks-following` doesn't work, but all this flag does is [preventing accessing FS to resolve a module path](https://github.com/timocov/dts-bundle-generator/blob/40d357b7ea2a5550ac0c5760727b53b7262a1e54/src/compile-dts.ts#L37-L39)). Probably it should be handled in `resolveModuleNames` to replace the file path with its request instead (but it might be tricky since it should be a path and ts could rely on it internally).
